provider: cloudngfwaws
major-version: 1
makeTemplate: bridged
providerDefaultBranch: main
# Use `pulumi convert` for translating examples from TF to Pulumi.
pulumiConvert: 1
# TODO: reenable this once https://github.com/pulumi/pulumi-terraform-bridge/issues/2586 is fixed
registryDocs: true
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
