provider: cloudngfwaws
major-version: 0
makeTemplate: bridged
providerDefaultBranch: main

plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter

actions:
  preTest:
    - name: make upstream
      run: make upstream

# Use `pulumi convert` for translating examples from TF to Pulumi.
pulumiConvert: 1
registryDocs: true

