// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAppIdVersionsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAppIdVersionsPlainArgs Empty = new GetAppIdVersionsPlainArgs();

    /**
     * Max number of results. Defaults to `100`.
     * 
     */
    @Import(name="maxResults")
    private @Nullable Integer maxResults;

    /**
     * @return Max number of results. Defaults to `100`.
     * 
     */
    public Optional<Integer> maxResults() {
        return Optional.ofNullable(this.maxResults);
    }

    /**
     * Pagination token.
     * 
     */
    @Import(name="token")
    private @Nullable String token;

    /**
     * @return Pagination token.
     * 
     */
    public Optional<String> token() {
        return Optional.ofNullable(this.token);
    }

    private GetAppIdVersionsPlainArgs() {}

    private GetAppIdVersionsPlainArgs(GetAppIdVersionsPlainArgs $) {
        this.maxResults = $.maxResults;
        this.token = $.token;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAppIdVersionsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAppIdVersionsPlainArgs $;

        public Builder() {
            $ = new GetAppIdVersionsPlainArgs();
        }

        public Builder(GetAppIdVersionsPlainArgs defaults) {
            $ = new GetAppIdVersionsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param maxResults Max number of results. Defaults to `100`.
         * 
         * @return builder
         * 
         */
        public Builder maxResults(@Nullable Integer maxResults) {
            $.maxResults = maxResults;
            return this;
        }

        /**
         * @param token Pagination token.
         * 
         * @return builder
         * 
         */
        public Builder token(@Nullable String token) {
            $.token = token;
            return this;
        }

        public GetAppIdVersionsPlainArgs build() {
            return $;
        }
    }

}
