// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetNgfwPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNgfwPlainArgs Empty = new GetNgfwPlainArgs();

    /**
     * The Firewall ID.
     * 
     */
    @Import(name="firewallId", required=true)
    private String firewallId;

    /**
     * @return The Firewall ID.
     * 
     */
    public String firewallId() {
        return this.firewallId;
    }

    private GetNgfwPlainArgs() {}

    private GetNgfwPlainArgs(GetNgfwPlainArgs $) {
        this.firewallId = $.firewallId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNgfwPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNgfwPlainArgs $;

        public Builder() {
            $ = new GetNgfwPlainArgs();
        }

        public Builder(GetNgfwPlainArgs defaults) {
            $ = new GetNgfwPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param firewallId The Firewall ID.
         * 
         * @return builder
         * 
         */
        public Builder firewallId(String firewallId) {
            $.firewallId = firewallId;
            return this;
        }

        public GetNgfwPlainArgs build() {
            if ($.firewallId == null) {
                throw new MissingRequiredPropertyException("GetNgfwPlainArgs", "firewallId");
            }
            return $;
        }
    }

}
