// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetNgfwPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNgfwPlainArgs Empty = new GetNgfwPlainArgs();

    /**
     * The account ID. This field is mandatory if using multiple accounts.
     * 
     */
    @Import(name="accountId")
    private @Nullable String accountId;

    /**
     * @return The account ID. This field is mandatory if using multiple accounts.
     * 
     */
    public Optional<String> accountId() {
        return Optional.ofNullable(this.accountId);
    }

    /**
     * The NGFW name.
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return The NGFW name.
     * 
     */
    public String name() {
        return this.name;
    }

    private GetNgfwPlainArgs() {}

    private GetNgfwPlainArgs(GetNgfwPlainArgs $) {
        this.accountId = $.accountId;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNgfwPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNgfwPlainArgs $;

        public Builder() {
            $ = new GetNgfwPlainArgs();
        }

        public Builder(GetNgfwPlainArgs defaults) {
            $ = new GetNgfwPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId The account ID. This field is mandatory if using multiple accounts.
         * 
         * @return builder
         * 
         */
        public Builder accountId(@Nullable String accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param name The NGFW name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public GetNgfwPlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetNgfwPlainArgs", "name");
            }
            return $;
        }
    }

}
