// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetNgfwLogProfileArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNgfwLogProfileArgs Empty = new GetNgfwLogProfileArgs();

    /**
     * The unique ID of the account.
     * 
     */
    @Import(name="accountId", required=true)
    private Output<String> accountId;

    /**
     * @return The unique ID of the account.
     * 
     */
    public Output<String> accountId() {
        return this.accountId;
    }

    /**
     * The name of the NGFW.
     * 
     */
    @Import(name="ngfw", required=true)
    private Output<String> ngfw;

    /**
     * @return The name of the NGFW.
     * 
     */
    public Output<String> ngfw() {
        return this.ngfw;
    }

    private GetNgfwLogProfileArgs() {}

    private GetNgfwLogProfileArgs(GetNgfwLogProfileArgs $) {
        this.accountId = $.accountId;
        this.ngfw = $.ngfw;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNgfwLogProfileArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNgfwLogProfileArgs $;

        public Builder() {
            $ = new GetNgfwLogProfileArgs();
        }

        public Builder(GetNgfwLogProfileArgs defaults) {
            $ = new GetNgfwLogProfileArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId The unique ID of the account.
         * 
         * @return builder
         * 
         */
        public Builder accountId(Output<String> accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param accountId The unique ID of the account.
         * 
         * @return builder
         * 
         */
        public Builder accountId(String accountId) {
            return accountId(Output.of(accountId));
        }

        /**
         * @param ngfw The name of the NGFW.
         * 
         * @return builder
         * 
         */
        public Builder ngfw(Output<String> ngfw) {
            $.ngfw = ngfw;
            return this;
        }

        /**
         * @param ngfw The name of the NGFW.
         * 
         * @return builder
         * 
         */
        public Builder ngfw(String ngfw) {
            return ngfw(Output.of(ngfw));
        }

        public GetNgfwLogProfileArgs build() {
            if ($.accountId == null) {
                throw new MissingRequiredPropertyException("GetNgfwLogProfileArgs", "accountId");
            }
            if ($.ngfw == null) {
                throw new MissingRequiredPropertyException("GetNgfwLogProfileArgs", "ngfw");
            }
            return $;
        }
    }

}
