// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws.inputs;

import com.pulumi.cloudngfwaws.inputs.NgfwSecurityZonePrefixPrivatePrefixArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NgfwSecurityZonePrefixArgs extends com.pulumi.resources.ResourceArgs {

    public static final NgfwSecurityZonePrefixArgs Empty = new NgfwSecurityZonePrefixArgs();

    @Import(name="privatePrefixes")
    private @Nullable Output<List<NgfwSecurityZonePrefixPrivatePrefixArgs>> privatePrefixes;

    public Optional<Output<List<NgfwSecurityZonePrefixPrivatePrefixArgs>>> privatePrefixes() {
        return Optional.ofNullable(this.privatePrefixes);
    }

    private NgfwSecurityZonePrefixArgs() {}

    private NgfwSecurityZonePrefixArgs(NgfwSecurityZonePrefixArgs $) {
        this.privatePrefixes = $.privatePrefixes;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NgfwSecurityZonePrefixArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NgfwSecurityZonePrefixArgs $;

        public Builder() {
            $ = new NgfwSecurityZonePrefixArgs();
        }

        public Builder(NgfwSecurityZonePrefixArgs defaults) {
            $ = new NgfwSecurityZonePrefixArgs(Objects.requireNonNull(defaults));
        }

        public Builder privatePrefixes(@Nullable Output<List<NgfwSecurityZonePrefixPrivatePrefixArgs>> privatePrefixes) {
            $.privatePrefixes = privatePrefixes;
            return this;
        }

        public Builder privatePrefixes(List<NgfwSecurityZonePrefixPrivatePrefixArgs> privatePrefixes) {
            return privatePrefixes(Output.of(privatePrefixes));
        }

        public Builder privatePrefixes(NgfwSecurityZonePrefixPrivatePrefixArgs... privatePrefixes) {
            return privatePrefixes(List.of(privatePrefixes));
        }

        public NgfwSecurityZonePrefixArgs build() {
            return $;
        }
    }

}
