// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NgfwStatusAttachmentArgs extends com.pulumi.resources.ResourceArgs {

    public static final NgfwStatusAttachmentArgs Empty = new NgfwStatusAttachmentArgs();

    /**
     * The endpoint id.
     * 
     */
    @Import(name="endpointId")
    private @Nullable Output<String> endpointId;

    /**
     * @return The endpoint id.
     * 
     */
    public Optional<Output<String>> endpointId() {
        return Optional.ofNullable(this.endpointId);
    }

    /**
     * The reject reason.
     * 
     */
    @Import(name="rejectedReason")
    private @Nullable Output<String> rejectedReason;

    /**
     * @return The reject reason.
     * 
     */
    public Optional<Output<String>> rejectedReason() {
        return Optional.ofNullable(this.rejectedReason);
    }

    /**
     * The attachment status.
     * 
     */
    @Import(name="status")
    private @Nullable Output<String> status;

    /**
     * @return The attachment status.
     * 
     */
    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * The subnet id.
     * 
     */
    @Import(name="subnetId")
    private @Nullable Output<String> subnetId;

    /**
     * @return The subnet id.
     * 
     */
    public Optional<Output<String>> subnetId() {
        return Optional.ofNullable(this.subnetId);
    }

    private NgfwStatusAttachmentArgs() {}

    private NgfwStatusAttachmentArgs(NgfwStatusAttachmentArgs $) {
        this.endpointId = $.endpointId;
        this.rejectedReason = $.rejectedReason;
        this.status = $.status;
        this.subnetId = $.subnetId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NgfwStatusAttachmentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NgfwStatusAttachmentArgs $;

        public Builder() {
            $ = new NgfwStatusAttachmentArgs();
        }

        public Builder(NgfwStatusAttachmentArgs defaults) {
            $ = new NgfwStatusAttachmentArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param endpointId The endpoint id.
         * 
         * @return builder
         * 
         */
        public Builder endpointId(@Nullable Output<String> endpointId) {
            $.endpointId = endpointId;
            return this;
        }

        /**
         * @param endpointId The endpoint id.
         * 
         * @return builder
         * 
         */
        public Builder endpointId(String endpointId) {
            return endpointId(Output.of(endpointId));
        }

        /**
         * @param rejectedReason The reject reason.
         * 
         * @return builder
         * 
         */
        public Builder rejectedReason(@Nullable Output<String> rejectedReason) {
            $.rejectedReason = rejectedReason;
            return this;
        }

        /**
         * @param rejectedReason The reject reason.
         * 
         * @return builder
         * 
         */
        public Builder rejectedReason(String rejectedReason) {
            return rejectedReason(Output.of(rejectedReason));
        }

        /**
         * @param status The attachment status.
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status The attachment status.
         * 
         * @return builder
         * 
         */
        public Builder status(String status) {
            return status(Output.of(status));
        }

        /**
         * @param subnetId The subnet id.
         * 
         * @return builder
         * 
         */
        public Builder subnetId(@Nullable Output<String> subnetId) {
            $.subnetId = subnetId;
            return this;
        }

        /**
         * @param subnetId The subnet id.
         * 
         * @return builder
         * 
         */
        public Builder subnetId(String subnetId) {
            return subnetId(Output.of(subnetId));
        }

        public NgfwStatusAttachmentArgs build() {
            return $;
        }
    }

}
