// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws
{
    public static class GetAppIdVersion
    {
        /// <summary>
        /// Data source to retrieve information on a given AppId version.
        /// 
        /// 
        /// ## Admin Permission Type
        /// 
        /// * `Rulestack`
        /// 
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using CloudNgfwAws = Pulumi.CloudNgfwAws;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = CloudNgfwAws.GetAppIdVersion.Invoke(new()
        ///     {
        ///         Version = "123-456",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetAppIdVersionResult> InvokeAsync(GetAppIdVersionArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAppIdVersionResult>("cloudngfwaws:index/getAppIdVersion:getAppIdVersion", args ?? new GetAppIdVersionArgs(), options.WithDefaults());

        /// <summary>
        /// Data source to retrieve information on a given AppId version.
        /// 
        /// 
        /// ## Admin Permission Type
        /// 
        /// * `Rulestack`
        /// 
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using CloudNgfwAws = Pulumi.CloudNgfwAws;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = CloudNgfwAws.GetAppIdVersion.Invoke(new()
        ///     {
        ///         Version = "123-456",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetAppIdVersionResult> Invoke(GetAppIdVersionInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAppIdVersionResult>("cloudngfwaws:index/getAppIdVersion:getAppIdVersion", args ?? new GetAppIdVersionInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAppIdVersionArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Max results. Defaults to `100`.
        /// </summary>
        [Input("maxResults")]
        public int? MaxResults { get; set; }

        /// <summary>
        /// Pagination token.
        /// </summary>
        [Input("token")]
        public string? Token { get; set; }

        /// <summary>
        /// The AppId version.
        /// </summary>
        [Input("version", required: true)]
        public string Version { get; set; } = null!;

        public GetAppIdVersionArgs()
        {
        }
        public static new GetAppIdVersionArgs Empty => new GetAppIdVersionArgs();
    }

    public sealed class GetAppIdVersionInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Max results. Defaults to `100`.
        /// </summary>
        [Input("maxResults")]
        public Input<int>? MaxResults { get; set; }

        /// <summary>
        /// Pagination token.
        /// </summary>
        [Input("token")]
        public Input<string>? Token { get; set; }

        /// <summary>
        /// The AppId version.
        /// </summary>
        [Input("version", required: true)]
        public Input<string> Version { get; set; } = null!;

        public GetAppIdVersionInvokeArgs()
        {
        }
        public static new GetAppIdVersionInvokeArgs Empty => new GetAppIdVersionInvokeArgs();
    }


    [OutputType]
    public sealed class GetAppIdVersionResult
    {
        /// <summary>
        /// List of applications.
        /// </summary>
        public readonly ImmutableArray<string> Applications;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Max results. Defaults to `100`.
        /// </summary>
        public readonly int? MaxResults;
        /// <summary>
        /// Token for the next page of results.
        /// </summary>
        public readonly string NextToken;
        /// <summary>
        /// Pagination token.
        /// </summary>
        public readonly string? Token;
        /// <summary>
        /// The AppId version.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetAppIdVersionResult(
            ImmutableArray<string> applications,

            string id,

            int? maxResults,

            string nextToken,

            string? token,

            string version)
        {
            Applications = applications;
            Id = id;
            MaxResults = maxResults;
            NextToken = nextToken;
            Token = token;
            Version = version;
        }
    }
}
