// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws
{
    /// <summary>
    /// Resource for NGFW manipulation.
    /// 
    /// &gt; **NOTE:** Having the `Rulestack` param reference the rulestack name from `cloudngfwaws.CommitRulestack` ensures that Terraform will only try to spin up a NGFW instance if the commit is successful.
    /// 
    /// ## Admin Permission Type
    /// 
    /// * `Firewall`
    /// 
    /// ## Configuration Guide
    /// 
    /// ***
    /// 
    /// ### V1 Schema — Existing Deployments Only
    /// 
    /// &gt; **Important:** V1 schema is for existing customers who already have firewalls deployed with Terraform.
    /// New firewalls must be created using the V2 schema.
    /// 
    /// ***
    /// 
    /// #### 1. Managing an Existing Firewall (no configuration changes)
    /// 
    /// Use the V1 schema as-is. No steps required beyond ensuring your existing state is in sync.
    /// 
    /// **Steps:**
    /// 
    /// 1. Verify there is no unintended drift:
    ///    2. If the plan is clean, no action needed. If drift is detected, review and apply:
    /// 
    /// **Full example — existing V1 firewall:**
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using CloudNgfwAws = Pulumi.CloudNgfwAws;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var rs = new CloudNgfwAws.Index.CommitRulestack("rs", new()
    ///     {
    ///         Rulestack = "my-rulestack",
    ///     });
    /// 
    ///     var example = new CloudNgfwAws.Index.Ngfw("example", new()
    ///     {
    ///         Name = "example-instance",
    ///         VpcId = exampleAwsVpc.Id,
    ///         AccountId = "111111111111",
    ///         Description = "Example description",
    ///         EndpointMode = "ServiceManaged",
    ///         SubnetMappings = new[]
    ///         {
    ///             new CloudNgfwAws.Inputs.NgfwSubnetMappingArgs
    ///             {
    ///                 SubnetId = subnet1.Id,
    ///             },
    ///             new CloudNgfwAws.Inputs.NgfwSubnetMappingArgs
    ///             {
    ///                 SubnetId = subnet2.Id,
    ///             },
    ///         },
    ///         Rulestack = rs.Rulestack,
    ///         Tags = 
    ///         {
    ///             { "Foo", "bar" },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ***
    /// 
    /// #### 2. Configuring Egress NAT on an Existing Firewall (V1)
    /// 
    /// Egress NAT can be added to an existing V1 firewall without recreating the resource.
    /// 
    /// &gt; `IpPoolType` accepts `AWSService` or `BYOIP`. Use `BYOIP` together with `IpamPoolId`
    /// if bringing your own IP pool.
    /// 
    /// **Steps:**
    /// 
    /// 1. Add the `EgressNat` block to your existing resource.
    /// 
    /// **Full example — existing V1 firewall with Egress NAT enabled:**
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using CloudNgfwAws = Pulumi.CloudNgfwAws;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new CloudNgfwAws.Index.Ngfw("example", new()
    ///     {
    ///         Name = "example-instance",
    ///         VpcId = "vpc-0a1b2c3d4e5f00001",
    ///         AccountId = "111111111111",
    ///         Description = "Example description",
    ///         EndpointMode = "CustomerManaged",
    ///         SubnetMappings = new[]
    ///         {
    ///             new CloudNgfwAws.Inputs.NgfwSubnetMappingArgs
    ///             {
    ///                 AvailabilityZone = "us-east-1a",
    ///             },
    ///             new CloudNgfwAws.Inputs.NgfwSubnetMappingArgs
    ///             {
    ///                 AvailabilityZone = "us-east-1c",
    ///             },
    ///         },
    ///         Rulestack = "my-rulestack",
    ///         EgressNats = new[]
    ///         {
    ///             new CloudNgfwAws.Inputs.NgfwEgressNatArgs
    ///             {
    ///                 Enabled = true,
    ///                 Settings = new[]
    ///                 {
    ///                     new CloudNgfwAws.Inputs.NgfwEgressNatSettingArgs
    ///                     {
    ///                         IpPoolType = "AWSService",
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///         Tags = 
    ///         {
    ///             { "Foo", "bar" },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// **To disable Egress NAT:** set `enabled = false` and re-apply.
    /// 
    /// ***
    /// 
    /// #### 3. Configuring Security Zones on an Existing Firewall (V1)
    /// 
    /// Security zones let you enable or disable Egress NAT per endpoint and add or remove private CIDR prefixes.
    /// 
    /// &gt; **Prerequisite:** Endpoints must be successfully created and in `ACCEPTED` state before
    /// security zones can be configured. Check `status.attachment[*].status` in Terraform state
    /// or the AWS console before proceeding.
    /// 
    /// **Steps:**
    /// 
    /// 1. Confirm endpoint status is `ACCEPTED`:
    /// 
    /// **To remove private prefixes:** remove the CIDR entries from `Cidrs` and re-apply.
    /// **To disable Egress NAT for a specific zone:** set `EgressNatEnabled = false` and re-apply.
    /// 
    /// ***
    /// 
    /// ### V2 Schema — New Firewalls
    /// 
    /// &gt; **Important:** New firewalls can only be created using the V2 schema. Use `AzList`
    /// instead of `SubnetMapping`, and `Endpoints` instead of `EndpointMode`/`SubnetMapping`.
    /// 
    /// ***
    /// 
    /// #### 1. Creating a New Firewall (V2)
    /// 
    /// Firewall creation uses `AzList` to specify availability zones.
    /// **Do not include `Endpoints` during creation** — they must be added in a separate update after the firewall is running.
    /// 
    /// **Steps:**
    /// 
    /// 1. Define the resource with `AzList` and no `Endpoints` block.
    /// 2. Proceed to **Step 2** once the firewall reaches `RUNNING` state.
    /// 
    /// **Full example — new V2 firewall (creation only):**
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using CloudNgfwAws = Pulumi.CloudNgfwAws;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new CloudNgfwAws.Index.Ngfw("example", new()
    ///     {
    ///         Name = "my-firewall",
    ///         Description = "My new firewall",
    ///         AzLists = new[]
    ///         {
    ///             "use1-az1",
    ///             "use1-az4",
    ///         },
    ///         AllowlistAccounts = new[]
    ///         {
    ///             "111111111111",
    ///         },
    ///         Tags = 
    ///         {
    ///             { "Owner", "my-team" },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ***
    /// 
    /// #### 2. Adding Endpoints to a V2 Firewall
    /// 
    /// Endpoints connect the firewall to customer VPCs. They must be added in a separate
    /// a separate update after the firewall is running.
    /// 
    /// **Steps:**
    /// 
    /// 1. Confirm the firewall status is `RUNNING`:
    /// 
    /// **Full example — V2 firewall with endpoints added:**
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using CloudNgfwAws = Pulumi.CloudNgfwAws;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new CloudNgfwAws.Index.Ngfw("example", new()
    ///     {
    ///         Name = "my-firewall",
    ///         Description = "My new firewall",
    ///         AzLists = new[]
    ///         {
    ///             "use1-az1",
    ///             "use1-az4",
    ///         },
    ///         AllowlistAccounts = new[]
    ///         {
    ///             "111111111111",
    ///         },
    ///         Endpoints = new[]
    ///         {
    ///             new CloudNgfwAws.Inputs.NgfwEndpointArgs
    ///             {
    ///                 AccountId = "111111111111",
    ///                 VpcId = "vpc-0a1b2c3d4e5f00002",
    ///                 SubnetId = "subnet-0a1b2c3d4e5f00001",
    ///                 Mode = "ServiceManaged",
    ///             },
    ///             new CloudNgfwAws.Inputs.NgfwEndpointArgs
    ///             {
    ///                 AccountId = "111111111111",
    ///                 VpcId = "vpc-0a1b2c3d4e5f00003",
    ///                 SubnetId = "subnet-0a1b2c3d4e5f00002",
    ///                 Mode = "ServiceManaged",
    ///             },
    ///         },
    ///         Tags = 
    ///         {
    ///             { "Owner", "my-team" },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ***
    /// 
    /// #### 3. Configuring Egress NAT on a V2 Firewall
    /// 
    /// Egress NAT can be enabled at the firewall level once at least one endpoint is accepted.
    /// 
    /// &gt; **Prerequisite:** At least one endpoint must be in `ACCEPTED` state.
    /// 
    /// **Steps:**
    /// 
    /// 1. Add the `EgressNat` block to the resource.
    /// 
    /// **Full example — V2 firewall with Egress NAT enabled:**
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using CloudNgfwAws = Pulumi.CloudNgfwAws;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new CloudNgfwAws.Index.Ngfw("example", new()
    ///     {
    ///         Name = "my-firewall",
    ///         Description = "My new firewall",
    ///         AzLists = new[]
    ///         {
    ///             "use1-az1",
    ///             "use1-az4",
    ///         },
    ///         AllowlistAccounts = new[]
    ///         {
    ///             "111111111111",
    ///         },
    ///         Endpoints = new[]
    ///         {
    ///             new CloudNgfwAws.Inputs.NgfwEndpointArgs
    ///             {
    ///                 AccountId = "111111111111",
    ///                 VpcId = "vpc-0a1b2c3d4e5f00002",
    ///                 SubnetId = "subnet-0a1b2c3d4e5f00001",
    ///                 Mode = "ServiceManaged",
    ///             },
    ///             new CloudNgfwAws.Inputs.NgfwEndpointArgs
    ///             {
    ///                 AccountId = "111111111111",
    ///                 VpcId = "vpc-0a1b2c3d4e5f00003",
    ///                 SubnetId = "subnet-0a1b2c3d4e5f00002",
    ///                 Mode = "ServiceManaged",
    ///             },
    ///         },
    ///         EgressNats = new[]
    ///         {
    ///             new CloudNgfwAws.Inputs.NgfwEgressNatArgs
    ///             {
    ///                 Enabled = true,
    ///                 Settings = new[]
    ///                 {
    ///                     new CloudNgfwAws.Inputs.NgfwEgressNatSettingArgs
    ///                     {
    ///                         IpPoolType = "AWSService",
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///         Tags = 
    ///         {
    ///             { "Owner", "my-team" },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// **To disable Egress NAT:** set `enabled = false` and re-apply.
    /// 
    /// ***
    /// 
    /// #### 4. Configuring Private Prefixes and Per-Endpoint Egress NAT (V2)
    /// 
    /// Once an endpoint is accepted, you can enable or disable Egress NAT and configure private
    /// CIDR prefixes on a per-endpoint basis within the `Endpoints` block.
    /// 
    /// &gt; **Prerequisite:** The endpoint must be in `ACCEPTED` state. The `EndpointId`
    /// is a read-only computed value — retrieve it from Terraform state after apply:
    /// 
    /// **To remove private prefixes:** remove the CIDR entries from `Cidrs` and re-apply.
    /// **To disable per-endpoint Egress NAT:** set `EgressNatEnabled = false` and re-apply.
    /// 
    /// ***
    /// 
    /// ## Import
    /// 
    /// import name is &lt;account_id&gt;:&lt;name&gt;
    /// 
    /// ```sh
    /// $ pulumi import cloudngfwaws:index/ngfw:Ngfw example 12345678:example-instance
    /// ```
    /// </summary>
    [CloudNgfwAwsResourceType("cloudngfwaws:index/ngfw:Ngfw")]
    public partial class Ngfw : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The Account Id.
        /// </summary>
        [Output("accountId")]
        public Output<string?> AccountId { get; private set; } = null!;

        /// <summary>
        /// The list of allowed accounts for this NGFW.
        /// </summary>
        [Output("allowlistAccounts")]
        public Output<ImmutableArray<string>> AllowlistAccounts { get; private set; } = null!;

        /// <summary>
        /// App-ID version number.
        /// </summary>
        [Output("appIdVersion")]
        public Output<string> AppIdVersion { get; private set; } = null!;

        /// <summary>
        /// Automatic App-ID upgrade version number. Defaults to `True`.
        /// </summary>
        [Output("automaticUpgradeAppIdVersion")]
        public Output<bool?> AutomaticUpgradeAppIdVersion { get; private set; } = null!;

        /// <summary>
        /// The list of availability zone IDs for this NGFW.
        /// </summary>
        [Output("azLists")]
        public Output<ImmutableArray<string>> AzLists { get; private set; } = null!;

        /// <summary>
        /// Enables or disables change protection for the NGFW.
        /// </summary>
        [Output("changeProtections")]
        public Output<ImmutableArray<string>> ChangeProtections { get; private set; } = null!;

        /// <summary>
        /// The update token.
        /// </summary>
        [Output("deploymentUpdateToken")]
        public Output<string> DeploymentUpdateToken { get; private set; } = null!;

        /// <summary>
        /// The NGFW description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("egressNats")]
        public Output<ImmutableArray<Outputs.NgfwEgressNat>> EgressNats { get; private set; } = null!;

        /// <summary>
        /// Set endpoint mode from the following options. Valid values are `ServiceManaged` or `CustomerManaged`.
        /// </summary>
        [Output("endpointMode")]
        public Output<string?> EndpointMode { get; private set; } = null!;

        /// <summary>
        /// The endpoint service name.
        /// </summary>
        [Output("endpointServiceName")]
        public Output<string> EndpointServiceName { get; private set; } = null!;

        [Output("endpoints")]
        public Output<ImmutableArray<Outputs.NgfwEndpoint>> Endpoints { get; private set; } = null!;

        /// <summary>
        /// The Firewall ID.
        /// </summary>
        [Output("firewallId")]
        public Output<string> FirewallId { get; private set; } = null!;

        /// <summary>
        /// The global rulestack for this NGFW.
        /// </summary>
        [Output("globalRulestack")]
        public Output<string?> GlobalRulestack { get; private set; } = null!;

        /// <summary>
        /// The link ID.
        /// </summary>
        [Output("linkId")]
        public Output<string> LinkId { get; private set; } = null!;

        /// <summary>
        /// The link status.
        /// </summary>
        [Output("linkStatus")]
        public Output<string> LinkStatus { get; private set; } = null!;

        /// <summary>
        /// Share NGFW with Multiple VPCs. This feature can be enabled only if the EndpointMode is CustomerManaged.
        /// </summary>
        [Output("multiVpc")]
        public Output<bool> MultiVpc { get; private set; } = null!;

        /// <summary>
        /// The NGFW name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("privateAccesses")]
        public Output<ImmutableArray<Outputs.NgfwPrivateAccess>> PrivateAccesses { get; private set; } = null!;

        /// <summary>
        /// The rulestack for this NGFW.
        /// </summary>
        [Output("rulestack")]
        public Output<string?> Rulestack { get; private set; } = null!;

        [Output("securityZones")]
        public Output<ImmutableArray<Outputs.NgfwSecurityZone>> SecurityZones { get; private set; } = null!;

        [Output("statuses")]
        public Output<ImmutableArray<Outputs.NgfwStatus>> Statuses { get; private set; } = null!;

        /// <summary>
        /// Subnet mappings.
        /// </summary>
        [Output("subnetMappings")]
        public Output<ImmutableArray<Outputs.NgfwSubnetMapping>> SubnetMappings { get; private set; } = null!;

        /// <summary>
        /// The tags.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableDictionary<string, string>> Tags { get; private set; } = null!;

        /// <summary>
        /// Firewall Instance Tier. Allowed values are 'base', 'standard', or 'premium'.
        /// </summary>
        [Output("tier")]
        public Output<string> Tier { get; private set; } = null!;

        /// <summary>
        /// The update token.
        /// </summary>
        [Output("updateToken")]
        public Output<string> UpdateToken { get; private set; } = null!;

        [Output("userIds")]
        public Output<ImmutableArray<Outputs.NgfwUserId>> UserIds { get; private set; } = null!;

        /// <summary>
        /// The VPC ID for the NGFW.
        /// </summary>
        [Output("vpcId")]
        public Output<string?> VpcId { get; private set; } = null!;


        /// <summary>
        /// Create a Ngfw resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Ngfw(string name, NgfwArgs? args = null, CustomResourceOptions? options = null)
            : base("cloudngfwaws:index/ngfw:Ngfw", name, args ?? new NgfwArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Ngfw(string name, Input<string> id, NgfwState? state = null, CustomResourceOptions? options = null)
            : base("cloudngfwaws:index/ngfw:Ngfw", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumi/pulumi-cloudngfwaws",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Ngfw resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Ngfw Get(string name, Input<string> id, NgfwState? state = null, CustomResourceOptions? options = null)
        {
            return new Ngfw(name, id, state, options);
        }
    }

    public sealed class NgfwArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Account Id.
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        [Input("allowlistAccounts")]
        private InputList<string>? _allowlistAccounts;

        /// <summary>
        /// The list of allowed accounts for this NGFW.
        /// </summary>
        public InputList<string> AllowlistAccounts
        {
            get => _allowlistAccounts ?? (_allowlistAccounts = new InputList<string>());
            set => _allowlistAccounts = value;
        }

        /// <summary>
        /// App-ID version number.
        /// </summary>
        [Input("appIdVersion")]
        public Input<string>? AppIdVersion { get; set; }

        /// <summary>
        /// Automatic App-ID upgrade version number. Defaults to `True`.
        /// </summary>
        [Input("automaticUpgradeAppIdVersion")]
        public Input<bool>? AutomaticUpgradeAppIdVersion { get; set; }

        [Input("azLists")]
        private InputList<string>? _azLists;

        /// <summary>
        /// The list of availability zone IDs for this NGFW.
        /// </summary>
        public InputList<string> AzLists
        {
            get => _azLists ?? (_azLists = new InputList<string>());
            set => _azLists = value;
        }

        [Input("changeProtections")]
        private InputList<string>? _changeProtections;

        /// <summary>
        /// Enables or disables change protection for the NGFW.
        /// </summary>
        public InputList<string> ChangeProtections
        {
            get => _changeProtections ?? (_changeProtections = new InputList<string>());
            set => _changeProtections = value;
        }

        /// <summary>
        /// The NGFW description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("egressNats")]
        private InputList<Inputs.NgfwEgressNatArgs>? _egressNats;
        public InputList<Inputs.NgfwEgressNatArgs> EgressNats
        {
            get => _egressNats ?? (_egressNats = new InputList<Inputs.NgfwEgressNatArgs>());
            set => _egressNats = value;
        }

        /// <summary>
        /// Set endpoint mode from the following options. Valid values are `ServiceManaged` or `CustomerManaged`.
        /// </summary>
        [Input("endpointMode")]
        public Input<string>? EndpointMode { get; set; }

        [Input("endpoints")]
        private InputList<Inputs.NgfwEndpointArgs>? _endpoints;
        public InputList<Inputs.NgfwEndpointArgs> Endpoints
        {
            get => _endpoints ?? (_endpoints = new InputList<Inputs.NgfwEndpointArgs>());
            set => _endpoints = value;
        }

        /// <summary>
        /// The Firewall ID.
        /// </summary>
        [Input("firewallId")]
        public Input<string>? FirewallId { get; set; }

        /// <summary>
        /// The global rulestack for this NGFW.
        /// </summary>
        [Input("globalRulestack")]
        public Input<string>? GlobalRulestack { get; set; }

        /// <summary>
        /// The link ID.
        /// </summary>
        [Input("linkId")]
        public Input<string>? LinkId { get; set; }

        /// <summary>
        /// Share NGFW with Multiple VPCs. This feature can be enabled only if the EndpointMode is CustomerManaged.
        /// </summary>
        [Input("multiVpc")]
        public Input<bool>? MultiVpc { get; set; }

        /// <summary>
        /// The NGFW name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("privateAccesses")]
        private InputList<Inputs.NgfwPrivateAccessArgs>? _privateAccesses;
        public InputList<Inputs.NgfwPrivateAccessArgs> PrivateAccesses
        {
            get => _privateAccesses ?? (_privateAccesses = new InputList<Inputs.NgfwPrivateAccessArgs>());
            set => _privateAccesses = value;
        }

        /// <summary>
        /// The rulestack for this NGFW.
        /// </summary>
        [Input("rulestack")]
        public Input<string>? Rulestack { get; set; }

        [Input("securityZones")]
        private InputList<Inputs.NgfwSecurityZoneArgs>? _securityZones;
        public InputList<Inputs.NgfwSecurityZoneArgs> SecurityZones
        {
            get => _securityZones ?? (_securityZones = new InputList<Inputs.NgfwSecurityZoneArgs>());
            set => _securityZones = value;
        }

        [Input("subnetMappings")]
        private InputList<Inputs.NgfwSubnetMappingArgs>? _subnetMappings;

        /// <summary>
        /// Subnet mappings.
        /// </summary>
        public InputList<Inputs.NgfwSubnetMappingArgs> SubnetMappings
        {
            get => _subnetMappings ?? (_subnetMappings = new InputList<Inputs.NgfwSubnetMappingArgs>());
            set => _subnetMappings = value;
        }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// The tags.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Firewall Instance Tier. Allowed values are 'base', 'standard', or 'premium'.
        /// </summary>
        [Input("tier")]
        public Input<string>? Tier { get; set; }

        [Input("userIds")]
        private InputList<Inputs.NgfwUserIdArgs>? _userIds;
        public InputList<Inputs.NgfwUserIdArgs> UserIds
        {
            get => _userIds ?? (_userIds = new InputList<Inputs.NgfwUserIdArgs>());
            set => _userIds = value;
        }

        /// <summary>
        /// The VPC ID for the NGFW.
        /// </summary>
        [Input("vpcId")]
        public Input<string>? VpcId { get; set; }

        public NgfwArgs()
        {
        }
        public static new NgfwArgs Empty => new NgfwArgs();
    }

    public sealed class NgfwState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Account Id.
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        [Input("allowlistAccounts")]
        private InputList<string>? _allowlistAccounts;

        /// <summary>
        /// The list of allowed accounts for this NGFW.
        /// </summary>
        public InputList<string> AllowlistAccounts
        {
            get => _allowlistAccounts ?? (_allowlistAccounts = new InputList<string>());
            set => _allowlistAccounts = value;
        }

        /// <summary>
        /// App-ID version number.
        /// </summary>
        [Input("appIdVersion")]
        public Input<string>? AppIdVersion { get; set; }

        /// <summary>
        /// Automatic App-ID upgrade version number. Defaults to `True`.
        /// </summary>
        [Input("automaticUpgradeAppIdVersion")]
        public Input<bool>? AutomaticUpgradeAppIdVersion { get; set; }

        [Input("azLists")]
        private InputList<string>? _azLists;

        /// <summary>
        /// The list of availability zone IDs for this NGFW.
        /// </summary>
        public InputList<string> AzLists
        {
            get => _azLists ?? (_azLists = new InputList<string>());
            set => _azLists = value;
        }

        [Input("changeProtections")]
        private InputList<string>? _changeProtections;

        /// <summary>
        /// Enables or disables change protection for the NGFW.
        /// </summary>
        public InputList<string> ChangeProtections
        {
            get => _changeProtections ?? (_changeProtections = new InputList<string>());
            set => _changeProtections = value;
        }

        /// <summary>
        /// The update token.
        /// </summary>
        [Input("deploymentUpdateToken")]
        public Input<string>? DeploymentUpdateToken { get; set; }

        /// <summary>
        /// The NGFW description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("egressNats")]
        private InputList<Inputs.NgfwEgressNatGetArgs>? _egressNats;
        public InputList<Inputs.NgfwEgressNatGetArgs> EgressNats
        {
            get => _egressNats ?? (_egressNats = new InputList<Inputs.NgfwEgressNatGetArgs>());
            set => _egressNats = value;
        }

        /// <summary>
        /// Set endpoint mode from the following options. Valid values are `ServiceManaged` or `CustomerManaged`.
        /// </summary>
        [Input("endpointMode")]
        public Input<string>? EndpointMode { get; set; }

        /// <summary>
        /// The endpoint service name.
        /// </summary>
        [Input("endpointServiceName")]
        public Input<string>? EndpointServiceName { get; set; }

        [Input("endpoints")]
        private InputList<Inputs.NgfwEndpointGetArgs>? _endpoints;
        public InputList<Inputs.NgfwEndpointGetArgs> Endpoints
        {
            get => _endpoints ?? (_endpoints = new InputList<Inputs.NgfwEndpointGetArgs>());
            set => _endpoints = value;
        }

        /// <summary>
        /// The Firewall ID.
        /// </summary>
        [Input("firewallId")]
        public Input<string>? FirewallId { get; set; }

        /// <summary>
        /// The global rulestack for this NGFW.
        /// </summary>
        [Input("globalRulestack")]
        public Input<string>? GlobalRulestack { get; set; }

        /// <summary>
        /// The link ID.
        /// </summary>
        [Input("linkId")]
        public Input<string>? LinkId { get; set; }

        /// <summary>
        /// The link status.
        /// </summary>
        [Input("linkStatus")]
        public Input<string>? LinkStatus { get; set; }

        /// <summary>
        /// Share NGFW with Multiple VPCs. This feature can be enabled only if the EndpointMode is CustomerManaged.
        /// </summary>
        [Input("multiVpc")]
        public Input<bool>? MultiVpc { get; set; }

        /// <summary>
        /// The NGFW name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("privateAccesses")]
        private InputList<Inputs.NgfwPrivateAccessGetArgs>? _privateAccesses;
        public InputList<Inputs.NgfwPrivateAccessGetArgs> PrivateAccesses
        {
            get => _privateAccesses ?? (_privateAccesses = new InputList<Inputs.NgfwPrivateAccessGetArgs>());
            set => _privateAccesses = value;
        }

        /// <summary>
        /// The rulestack for this NGFW.
        /// </summary>
        [Input("rulestack")]
        public Input<string>? Rulestack { get; set; }

        [Input("securityZones")]
        private InputList<Inputs.NgfwSecurityZoneGetArgs>? _securityZones;
        public InputList<Inputs.NgfwSecurityZoneGetArgs> SecurityZones
        {
            get => _securityZones ?? (_securityZones = new InputList<Inputs.NgfwSecurityZoneGetArgs>());
            set => _securityZones = value;
        }

        [Input("statuses")]
        private InputList<Inputs.NgfwStatusGetArgs>? _statuses;
        public InputList<Inputs.NgfwStatusGetArgs> Statuses
        {
            get => _statuses ?? (_statuses = new InputList<Inputs.NgfwStatusGetArgs>());
            set => _statuses = value;
        }

        [Input("subnetMappings")]
        private InputList<Inputs.NgfwSubnetMappingGetArgs>? _subnetMappings;

        /// <summary>
        /// Subnet mappings.
        /// </summary>
        public InputList<Inputs.NgfwSubnetMappingGetArgs> SubnetMappings
        {
            get => _subnetMappings ?? (_subnetMappings = new InputList<Inputs.NgfwSubnetMappingGetArgs>());
            set => _subnetMappings = value;
        }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// The tags.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Firewall Instance Tier. Allowed values are 'base', 'standard', or 'premium'.
        /// </summary>
        [Input("tier")]
        public Input<string>? Tier { get; set; }

        /// <summary>
        /// The update token.
        /// </summary>
        [Input("updateToken")]
        public Input<string>? UpdateToken { get; set; }

        [Input("userIds")]
        private InputList<Inputs.NgfwUserIdGetArgs>? _userIds;
        public InputList<Inputs.NgfwUserIdGetArgs> UserIds
        {
            get => _userIds ?? (_userIds = new InputList<Inputs.NgfwUserIdGetArgs>());
            set => _userIds = value;
        }

        /// <summary>
        /// The VPC ID for the NGFW.
        /// </summary>
        [Input("vpcId")]
        public Input<string>? VpcId { get; set; }

        public NgfwState()
        {
        }
        public static new NgfwState Empty => new NgfwState();
    }
}
