// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cloudngfwaws

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-cloudngfwaws/sdk/go/cloudngfwaws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Data source for retrieving account information.
//
// ## Admin Permission Type
//
// * `Rulestack` (for `scope="Local"`)
// * `Global Rulestack` (for `scope="Global"`)
func LookupAccount(ctx *pulumi.Context, args *LookupAccountArgs, opts ...pulumi.InvokeOption) (*LookupAccountResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAccountResult
	err := ctx.Invoke("cloudngfwaws:index/getAccount:getAccount", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAccount.
type LookupAccountArgs struct {
	// The account ID
	AccountId *string `pulumi:"accountId"`
	// The CFT URL.
	CftUrl *string `pulumi:"cftUrl"`
	// The external ID of the account
	ExternalId *string `pulumi:"externalId"`
	// The Account onboarding status
	OnboardingStatus *string `pulumi:"onboardingStatus"`
	// Origin of account onboarding
	Origin *string `pulumi:"origin"`
	// The account ID of cloud NGFW service
	ServiceAccountId *string `pulumi:"serviceAccountId"`
	// The SNS topic ARN
	SnsTopicArn *string `pulumi:"snsTopicArn"`
	// The trusted account ID
	TrustedAccount *string `pulumi:"trustedAccount"`
}

// A collection of values returned by getAccount.
type LookupAccountResult struct {
	// The account ID
	AccountId *string `pulumi:"accountId"`
	// The CFT URL.
	CftUrl string `pulumi:"cftUrl"`
	// The external ID of the account
	ExternalId string `pulumi:"externalId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The Account onboarding status
	OnboardingStatus string `pulumi:"onboardingStatus"`
	// Origin of account onboarding
	Origin string `pulumi:"origin"`
	// The account ID of cloud NGFW service
	ServiceAccountId string `pulumi:"serviceAccountId"`
	// The SNS topic ARN
	SnsTopicArn string `pulumi:"snsTopicArn"`
	// The trusted account ID
	TrustedAccount string `pulumi:"trustedAccount"`
	// The update token.
	UpdateToken string `pulumi:"updateToken"`
}

func LookupAccountOutput(ctx *pulumi.Context, args LookupAccountOutputArgs, opts ...pulumi.InvokeOption) LookupAccountResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupAccountResultOutput, error) {
			args := v.(LookupAccountArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cloudngfwaws:index/getAccount:getAccount", args, LookupAccountResultOutput{}, options).(LookupAccountResultOutput), nil
		}).(LookupAccountResultOutput)
}

// A collection of arguments for invoking getAccount.
type LookupAccountOutputArgs struct {
	// The account ID
	AccountId pulumi.StringPtrInput `pulumi:"accountId"`
	// The CFT URL.
	CftUrl pulumi.StringPtrInput `pulumi:"cftUrl"`
	// The external ID of the account
	ExternalId pulumi.StringPtrInput `pulumi:"externalId"`
	// The Account onboarding status
	OnboardingStatus pulumi.StringPtrInput `pulumi:"onboardingStatus"`
	// Origin of account onboarding
	Origin pulumi.StringPtrInput `pulumi:"origin"`
	// The account ID of cloud NGFW service
	ServiceAccountId pulumi.StringPtrInput `pulumi:"serviceAccountId"`
	// The SNS topic ARN
	SnsTopicArn pulumi.StringPtrInput `pulumi:"snsTopicArn"`
	// The trusted account ID
	TrustedAccount pulumi.StringPtrInput `pulumi:"trustedAccount"`
}

func (LookupAccountOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAccountArgs)(nil)).Elem()
}

// A collection of values returned by getAccount.
type LookupAccountResultOutput struct{ *pulumi.OutputState }

func (LookupAccountResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAccountResult)(nil)).Elem()
}

func (o LookupAccountResultOutput) ToLookupAccountResultOutput() LookupAccountResultOutput {
	return o
}

func (o LookupAccountResultOutput) ToLookupAccountResultOutputWithContext(ctx context.Context) LookupAccountResultOutput {
	return o
}

// The account ID
func (o LookupAccountResultOutput) AccountId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupAccountResult) *string { return v.AccountId }).(pulumi.StringPtrOutput)
}

// The CFT URL.
func (o LookupAccountResultOutput) CftUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.CftUrl }).(pulumi.StringOutput)
}

// The external ID of the account
func (o LookupAccountResultOutput) ExternalId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.ExternalId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupAccountResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.Id }).(pulumi.StringOutput)
}

// The Account onboarding status
func (o LookupAccountResultOutput) OnboardingStatus() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.OnboardingStatus }).(pulumi.StringOutput)
}

// Origin of account onboarding
func (o LookupAccountResultOutput) Origin() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.Origin }).(pulumi.StringOutput)
}

// The account ID of cloud NGFW service
func (o LookupAccountResultOutput) ServiceAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.ServiceAccountId }).(pulumi.StringOutput)
}

// The SNS topic ARN
func (o LookupAccountResultOutput) SnsTopicArn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.SnsTopicArn }).(pulumi.StringOutput)
}

// The trusted account ID
func (o LookupAccountResultOutput) TrustedAccount() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.TrustedAccount }).(pulumi.StringOutput)
}

// The update token.
func (o LookupAccountResultOutput) UpdateToken() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccountResult) string { return v.UpdateToken }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAccountResultOutput{})
}
