// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws.Outputs
{

    [OutputType]
    public sealed class GetAccountsAccountDetailResult
    {
        /// <summary>
        /// The account id.
        /// </summary>
        public readonly string AccountId;
        /// <summary>
        /// External Id of the onboarded account
        /// </summary>
        public readonly string ExternalId;
        /// <summary>
        /// Onboarding status of the account.
        /// </summary>
        public readonly string OnboardingStatus;

        [OutputConstructor]
        private GetAccountsAccountDetailResult(
            string accountId,

            string externalId,

            string onboardingStatus)
        {
            AccountId = accountId;
            ExternalId = externalId;
            OnboardingStatus = onboardingStatus;
        }
    }
}
