// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws.Outputs
{

    [OutputType]
    public sealed class GetNgfwSubnetMappingResult
    {
        /// <summary>
        /// The availability zone, for when the endpoint mode is customer managed.
        /// </summary>
        public readonly string AvailabilityZone;
        /// <summary>
        /// The availability zone ID, for when the endpoint mode is customer managed.
        /// </summary>
        public readonly string AvailabilityZoneId;
        /// <summary>
        /// The subnet id, for when the endpoint mode is service managed.
        /// </summary>
        public readonly string SubnetId;

        [OutputConstructor]
        private GetNgfwSubnetMappingResult(
            string availabilityZone,

            string availabilityZoneId,

            string subnetId)
        {
            AvailabilityZone = availabilityZone;
            AvailabilityZoneId = availabilityZoneId;
            SubnetId = subnetId;
        }
    }
}
