// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws.Outputs
{

    [OutputType]
    public sealed class GetNgfwSecurityZonePrefixPrivatePrefixResult
    {
        public readonly ImmutableArray<string> Cidrs;

        [OutputConstructor]
        private GetNgfwSecurityZonePrefixPrivatePrefixResult(ImmutableArray<string> cidrs)
        {
            Cidrs = cidrs;
        }
    }
}
