// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws.Outputs
{

    [OutputType]
    public sealed class NgfwStatusAttachment
    {
        /// <summary>
        /// The endpoint id.
        /// </summary>
        public readonly string? EndpointId;
        /// <summary>
        /// The reject reason.
        /// </summary>
        public readonly string? RejectedReason;
        /// <summary>
        /// The attachment status.
        /// </summary>
        public readonly string? Status;
        /// <summary>
        /// The subnet id.
        /// </summary>
        public readonly string? SubnetId;

        [OutputConstructor]
        private NgfwStatusAttachment(
            string? endpointId,

            string? rejectedReason,

            string? status,

            string? subnetId)
        {
            EndpointId = endpointId;
            RejectedReason = rejectedReason;
            Status = status;
            SubnetId = subnetId;
        }
    }
}
