// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws.Outputs
{

    [OutputType]
    public sealed class NgfwUserId
    {
        /// <summary>
        /// Agent Name for UserID
        /// </summary>
        public readonly string? AgentName;
        /// <summary>
        /// The Collector Name
        /// </summary>
        public readonly string? CollectorName;
        /// <summary>
        /// List of Custom Include Exclude Networks
        /// </summary>
        public readonly ImmutableArray<Outputs.NgfwUserIdCustomIncludeExcludeNetwork> CustomIncludeExcludeNetworks;
        /// <summary>
        /// Enable UserID Config
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// The Port
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// AWS Secret Key ARN
        /// </summary>
        public readonly string? SecretKeyArn;
        /// <summary>
        /// Status and State of UserID Configuration
        /// </summary>
        public readonly string? UserIdStatus;

        [OutputConstructor]
        private NgfwUserId(
            string? agentName,

            string? collectorName,

            ImmutableArray<Outputs.NgfwUserIdCustomIncludeExcludeNetwork> customIncludeExcludeNetworks,

            bool enabled,

            int port,

            string? secretKeyArn,

            string? userIdStatus)
        {
            AgentName = agentName;
            CollectorName = collectorName;
            CustomIncludeExcludeNetworks = customIncludeExcludeNetworks;
            Enabled = enabled;
            Port = port;
            SecretKeyArn = secretKeyArn;
            UserIdStatus = userIdStatus;
        }
    }
}
