// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws.Outputs
{

    [OutputType]
    public sealed class NgfwSecurityZonePrefix
    {
        public readonly ImmutableArray<Outputs.NgfwSecurityZonePrefixPrivatePrefix> PrivatePrefixes;

        [OutputConstructor]
        private NgfwSecurityZonePrefix(ImmutableArray<Outputs.NgfwSecurityZonePrefixPrivatePrefix> privatePrefixes)
        {
            PrivatePrefixes = privatePrefixes;
        }
    }
}
