// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws.Outputs
{

    [OutputType]
    public sealed class RulestackProfileConfig
    {
        /// <summary>
        /// Anti-spyware profile setting. Defaults to `BestPractice`.
        /// </summary>
        public readonly string? AntiSpyware;
        /// <summary>
        /// Anti-virus profile setting. Defaults to `BestPractice`.
        /// </summary>
        public readonly string? AntiVirus;
        /// <summary>
        /// File blocking profile setting. Defaults to `BestPractice`.
        /// </summary>
        public readonly string? FileBlocking;
        /// <summary>
        /// Outbound trust certificate.
        /// </summary>
        public readonly string? OutboundTrustCertificate;
        /// <summary>
        /// Outbound untrust certificate.
        /// </summary>
        public readonly string? OutboundUntrustCertificate;
        /// <summary>
        /// URL filtering profile setting. Defaults to `None`.
        /// </summary>
        public readonly string? UrlFiltering;
        /// <summary>
        /// Vulnerability profile setting. Defaults to `BestPractice`.
        /// </summary>
        public readonly string? Vulnerability;

        [OutputConstructor]
        private RulestackProfileConfig(
            string? antiSpyware,

            string? antiVirus,

            string? fileBlocking,

            string? outboundTrustCertificate,

            string? outboundUntrustCertificate,

            string? urlFiltering,

            string? vulnerability)
        {
            AntiSpyware = antiSpyware;
            AntiVirus = antiVirus;
            FileBlocking = fileBlocking;
            OutboundTrustCertificate = outboundTrustCertificate;
            OutboundUntrustCertificate = outboundUntrustCertificate;
            UrlFiltering = urlFiltering;
            Vulnerability = vulnerability;
        }
    }
}
