// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetCountryResult {
    /**
     * @return The country code (as the key) and description (as the value).
     * 
     */
    private Map<String,String> codes;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return Max number of results. Defaults to `100`.
     * 
     */
    private @Nullable Integer maxResults;
    /**
     * @return Token for the next page of results.
     * 
     */
    private String nextToken;
    /**
     * @return Pagination token.
     * 
     */
    private @Nullable String token;

    private GetCountryResult() {}
    /**
     * @return The country code (as the key) and description (as the value).
     * 
     */
    public Map<String,String> codes() {
        return this.codes;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Max number of results. Defaults to `100`.
     * 
     */
    public Optional<Integer> maxResults() {
        return Optional.ofNullable(this.maxResults);
    }
    /**
     * @return Token for the next page of results.
     * 
     */
    public String nextToken() {
        return this.nextToken;
    }
    /**
     * @return Pagination token.
     * 
     */
    public Optional<String> token() {
        return Optional.ofNullable(this.token);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCountryResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Map<String,String> codes;
        private String id;
        private @Nullable Integer maxResults;
        private String nextToken;
        private @Nullable String token;
        public Builder() {}
        public Builder(GetCountryResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.codes = defaults.codes;
    	      this.id = defaults.id;
    	      this.maxResults = defaults.maxResults;
    	      this.nextToken = defaults.nextToken;
    	      this.token = defaults.token;
        }

        @CustomType.Setter
        public Builder codes(Map<String,String> codes) {
            if (codes == null) {
              throw new MissingRequiredPropertyException("GetCountryResult", "codes");
            }
            this.codes = codes;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetCountryResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder maxResults(@Nullable Integer maxResults) {

            this.maxResults = maxResults;
            return this;
        }
        @CustomType.Setter
        public Builder nextToken(String nextToken) {
            if (nextToken == null) {
              throw new MissingRequiredPropertyException("GetCountryResult", "nextToken");
            }
            this.nextToken = nextToken;
            return this;
        }
        @CustomType.Setter
        public Builder token(@Nullable String token) {

            this.token = token;
            return this;
        }
        public GetCountryResult build() {
            final var _resultValue = new GetCountryResult();
            _resultValue.codes = codes;
            _resultValue.id = id;
            _resultValue.maxResults = maxResults;
            _resultValue.nextToken = nextToken;
            _resultValue.token = token;
            return _resultValue;
        }
    }
}
