// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetIntelligentFeedResult {
    /**
     * @return The audit comment.
     * 
     */
    private String auditComment;
    /**
     * @return The certificate profile.
     * 
     */
    private String certificate;
    /**
     * @return Retrieve either the candidate or running config. Valid values are `candidate` or `running`. Defaults to `candidate`.
     * 
     */
    private @Nullable String configType;
    /**
     * @return The description.
     * 
     */
    private String description;
    /**
     * @return Update frequency. Valid values are `HOURLY` or `DAILY`.
     * 
     */
    private String frequency;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The name.
     * 
     */
    private String name;
    /**
     * @return The rulestack.
     * 
     */
    private String rulestack;
    /**
     * @return The rulestack&#39;s scope. A local rulestack will require that you&#39;ve retrieved a LRA JWT. A global rulestack will require that you&#39;ve retrieved a GRA JWT. Valid values are `Local` or `Global`. Defaults to `Local`.
     * 
     */
    private @Nullable String scope;
    /**
     * @return The time to poll for updates if frequency is daily. The number must be between [0, 23] incluside.
     * 
     */
    private Integer time;
    /**
     * @return The intelligent feed type. Valid values are `IP_LIST` or `URL_LIST`.
     * 
     */
    private String type;
    /**
     * @return The update token.
     * 
     */
    private String updateToken;
    /**
     * @return The intelligent feed source.
     * 
     */
    private String url;

    private GetIntelligentFeedResult() {}
    /**
     * @return The audit comment.
     * 
     */
    public String auditComment() {
        return this.auditComment;
    }
    /**
     * @return The certificate profile.
     * 
     */
    public String certificate() {
        return this.certificate;
    }
    /**
     * @return Retrieve either the candidate or running config. Valid values are `candidate` or `running`. Defaults to `candidate`.
     * 
     */
    public Optional<String> configType() {
        return Optional.ofNullable(this.configType);
    }
    /**
     * @return The description.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return Update frequency. Valid values are `HOURLY` or `DAILY`.
     * 
     */
    public String frequency() {
        return this.frequency;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The name.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The rulestack.
     * 
     */
    public String rulestack() {
        return this.rulestack;
    }
    /**
     * @return The rulestack&#39;s scope. A local rulestack will require that you&#39;ve retrieved a LRA JWT. A global rulestack will require that you&#39;ve retrieved a GRA JWT. Valid values are `Local` or `Global`. Defaults to `Local`.
     * 
     */
    public Optional<String> scope() {
        return Optional.ofNullable(this.scope);
    }
    /**
     * @return The time to poll for updates if frequency is daily. The number must be between [0, 23] incluside.
     * 
     */
    public Integer time() {
        return this.time;
    }
    /**
     * @return The intelligent feed type. Valid values are `IP_LIST` or `URL_LIST`.
     * 
     */
    public String type() {
        return this.type;
    }
    /**
     * @return The update token.
     * 
     */
    public String updateToken() {
        return this.updateToken;
    }
    /**
     * @return The intelligent feed source.
     * 
     */
    public String url() {
        return this.url;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetIntelligentFeedResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String auditComment;
        private String certificate;
        private @Nullable String configType;
        private String description;
        private String frequency;
        private String id;
        private String name;
        private String rulestack;
        private @Nullable String scope;
        private Integer time;
        private String type;
        private String updateToken;
        private String url;
        public Builder() {}
        public Builder(GetIntelligentFeedResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.auditComment = defaults.auditComment;
    	      this.certificate = defaults.certificate;
    	      this.configType = defaults.configType;
    	      this.description = defaults.description;
    	      this.frequency = defaults.frequency;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.rulestack = defaults.rulestack;
    	      this.scope = defaults.scope;
    	      this.time = defaults.time;
    	      this.type = defaults.type;
    	      this.updateToken = defaults.updateToken;
    	      this.url = defaults.url;
        }

        @CustomType.Setter
        public Builder auditComment(String auditComment) {
            if (auditComment == null) {
              throw new MissingRequiredPropertyException("GetIntelligentFeedResult", "auditComment");
            }
            this.auditComment = auditComment;
            return this;
        }
        @CustomType.Setter
        public Builder certificate(String certificate) {
            if (certificate == null) {
              throw new MissingRequiredPropertyException("GetIntelligentFeedResult", "certificate");
            }
            this.certificate = certificate;
            return this;
        }
        @CustomType.Setter
        public Builder configType(@Nullable String configType) {

            this.configType = configType;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetIntelligentFeedResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder frequency(String frequency) {
            if (frequency == null) {
              throw new MissingRequiredPropertyException("GetIntelligentFeedResult", "frequency");
            }
            this.frequency = frequency;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetIntelligentFeedResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetIntelligentFeedResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder rulestack(String rulestack) {
            if (rulestack == null) {
              throw new MissingRequiredPropertyException("GetIntelligentFeedResult", "rulestack");
            }
            this.rulestack = rulestack;
            return this;
        }
        @CustomType.Setter
        public Builder scope(@Nullable String scope) {

            this.scope = scope;
            return this;
        }
        @CustomType.Setter
        public Builder time(Integer time) {
            if (time == null) {
              throw new MissingRequiredPropertyException("GetIntelligentFeedResult", "time");
            }
            this.time = time;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetIntelligentFeedResult", "type");
            }
            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder updateToken(String updateToken) {
            if (updateToken == null) {
              throw new MissingRequiredPropertyException("GetIntelligentFeedResult", "updateToken");
            }
            this.updateToken = updateToken;
            return this;
        }
        @CustomType.Setter
        public Builder url(String url) {
            if (url == null) {
              throw new MissingRequiredPropertyException("GetIntelligentFeedResult", "url");
            }
            this.url = url;
            return this;
        }
        public GetIntelligentFeedResult build() {
            final var _resultValue = new GetIntelligentFeedResult();
            _resultValue.auditComment = auditComment;
            _resultValue.certificate = certificate;
            _resultValue.configType = configType;
            _resultValue.description = description;
            _resultValue.frequency = frequency;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.rulestack = rulestack;
            _resultValue.scope = scope;
            _resultValue.time = time;
            _resultValue.type = type;
            _resultValue.updateToken = updateToken;
            _resultValue.url = url;
            return _resultValue;
        }
    }
}
