// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws.outputs;

import com.pulumi.cloudngfwaws.outputs.GetNgfwEndpointPrefixPrivatePrefix;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNgfwEndpointPrefix {
    private List<GetNgfwEndpointPrefixPrivatePrefix> privatePrefixes;

    private GetNgfwEndpointPrefix() {}
    public List<GetNgfwEndpointPrefixPrivatePrefix> privatePrefixes() {
        return this.privatePrefixes;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNgfwEndpointPrefix defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetNgfwEndpointPrefixPrivatePrefix> privatePrefixes;
        public Builder() {}
        public Builder(GetNgfwEndpointPrefix defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.privatePrefixes = defaults.privatePrefixes;
        }

        @CustomType.Setter
        public Builder privatePrefixes(List<GetNgfwEndpointPrefixPrivatePrefix> privatePrefixes) {
            if (privatePrefixes == null) {
              throw new MissingRequiredPropertyException("GetNgfwEndpointPrefix", "privatePrefixes");
            }
            this.privatePrefixes = privatePrefixes;
            return this;
        }
        public Builder privatePrefixes(GetNgfwEndpointPrefixPrivatePrefix... privatePrefixes) {
            return privatePrefixes(List.of(privatePrefixes));
        }
        public GetNgfwEndpointPrefix build() {
            final var _resultValue = new GetNgfwEndpointPrefix();
            _resultValue.privatePrefixes = privatePrefixes;
            return _resultValue;
        }
    }
}
