// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws.outputs;

import com.pulumi.cloudngfwaws.outputs.GetNgfwStatusAttachment;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNgfwStatus {
    /**
     * @return The firewall attachments.
     * 
     */
    private List<GetNgfwStatusAttachment> attachments;
    /**
     * @return The firewall failure reason.
     * 
     */
    private String failureReason;
    /**
     * @return The firewall status.
     * 
     */
    private String firewallStatus;
    /**
     * @return The rulestack status.
     * 
     */
    private String rulestackStatus;

    private GetNgfwStatus() {}
    /**
     * @return The firewall attachments.
     * 
     */
    public List<GetNgfwStatusAttachment> attachments() {
        return this.attachments;
    }
    /**
     * @return The firewall failure reason.
     * 
     */
    public String failureReason() {
        return this.failureReason;
    }
    /**
     * @return The firewall status.
     * 
     */
    public String firewallStatus() {
        return this.firewallStatus;
    }
    /**
     * @return The rulestack status.
     * 
     */
    public String rulestackStatus() {
        return this.rulestackStatus;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNgfwStatus defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetNgfwStatusAttachment> attachments;
        private String failureReason;
        private String firewallStatus;
        private String rulestackStatus;
        public Builder() {}
        public Builder(GetNgfwStatus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.attachments = defaults.attachments;
    	      this.failureReason = defaults.failureReason;
    	      this.firewallStatus = defaults.firewallStatus;
    	      this.rulestackStatus = defaults.rulestackStatus;
        }

        @CustomType.Setter
        public Builder attachments(List<GetNgfwStatusAttachment> attachments) {
            if (attachments == null) {
              throw new MissingRequiredPropertyException("GetNgfwStatus", "attachments");
            }
            this.attachments = attachments;
            return this;
        }
        public Builder attachments(GetNgfwStatusAttachment... attachments) {
            return attachments(List.of(attachments));
        }
        @CustomType.Setter
        public Builder failureReason(String failureReason) {
            if (failureReason == null) {
              throw new MissingRequiredPropertyException("GetNgfwStatus", "failureReason");
            }
            this.failureReason = failureReason;
            return this;
        }
        @CustomType.Setter
        public Builder firewallStatus(String firewallStatus) {
            if (firewallStatus == null) {
              throw new MissingRequiredPropertyException("GetNgfwStatus", "firewallStatus");
            }
            this.firewallStatus = firewallStatus;
            return this;
        }
        @CustomType.Setter
        public Builder rulestackStatus(String rulestackStatus) {
            if (rulestackStatus == null) {
              throw new MissingRequiredPropertyException("GetNgfwStatus", "rulestackStatus");
            }
            this.rulestackStatus = rulestackStatus;
            return this;
        }
        public GetNgfwStatus build() {
            final var _resultValue = new GetNgfwStatus();
            _resultValue.attachments = attachments;
            _resultValue.failureReason = failureReason;
            _resultValue.firewallStatus = firewallStatus;
            _resultValue.rulestackStatus = rulestackStatus;
            return _resultValue;
        }
    }
}
