// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetNgfwEgressNatSetting {
    /**
     * @return Set ip pool type from the following options. Valid values are `AWSService` or `BYOIP`.
     * 
     */
    private String ipPoolType;
    /**
     * @return The IP pool ID
     * 
     */
    private String ipamPoolId;

    private GetNgfwEgressNatSetting() {}
    /**
     * @return Set ip pool type from the following options. Valid values are `AWSService` or `BYOIP`.
     * 
     */
    public String ipPoolType() {
        return this.ipPoolType;
    }
    /**
     * @return The IP pool ID
     * 
     */
    public String ipamPoolId() {
        return this.ipamPoolId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNgfwEgressNatSetting defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String ipPoolType;
        private String ipamPoolId;
        public Builder() {}
        public Builder(GetNgfwEgressNatSetting defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ipPoolType = defaults.ipPoolType;
    	      this.ipamPoolId = defaults.ipamPoolId;
        }

        @CustomType.Setter
        public Builder ipPoolType(String ipPoolType) {
            if (ipPoolType == null) {
              throw new MissingRequiredPropertyException("GetNgfwEgressNatSetting", "ipPoolType");
            }
            this.ipPoolType = ipPoolType;
            return this;
        }
        @CustomType.Setter
        public Builder ipamPoolId(String ipamPoolId) {
            if (ipamPoolId == null) {
              throw new MissingRequiredPropertyException("GetNgfwEgressNatSetting", "ipamPoolId");
            }
            this.ipamPoolId = ipamPoolId;
            return this;
        }
        public GetNgfwEgressNatSetting build() {
            final var _resultValue = new GetNgfwEgressNatSetting();
            _resultValue.ipPoolType = ipPoolType;
            _resultValue.ipamPoolId = ipamPoolId;
            return _resultValue;
        }
    }
}
