// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws;

import com.pulumi.cloudngfwaws.IntelligentFeedArgs;
import com.pulumi.cloudngfwaws.Utilities;
import com.pulumi.cloudngfwaws.inputs.IntelligentFeedState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Resource for intelligent feed manipulation.
 * 
 * ## Admin Permission Type
 * 
 * * `Rulestack` (for `scope=&#34;Local&#34;`)
 * * `Global Rulestack` (for `scope=&#34;Global&#34;`)
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.cloudngfwaws.Rulestack;
 * import com.pulumi.cloudngfwaws.RulestackArgs;
 * import com.pulumi.cloudngfwaws.inputs.RulestackProfileConfigArgs;
 * import com.pulumi.cloudngfwaws.IntelligentFeed;
 * import com.pulumi.cloudngfwaws.IntelligentFeedArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var r = new Rulestack("r", RulestackArgs.builder()
 *             .name("terraform-rulestack")
 *             .scope("Local")
 *             .accountId("123456789")
 *             .description("Made by Pulumi")
 *             .profileConfig(RulestackProfileConfigArgs.builder()
 *                 .antiSpyware("BestPractice")
 *                 .build())
 *             .build());
 * 
 *         // Retrieve the feed information every day at midnight.
 *         var example = new IntelligentFeed("example", IntelligentFeedArgs.builder()
 *             .rulestack(r.name())
 *             .name("tf-feed")
 *             .description("Also configured by Terraform")
 *             .url("https://foobar.net")
 *             .type("URL_LIST")
 *             .frequency("DAILY")
 *             .time(0)
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * import name is &lt;scope&gt;:&lt;rulestack&gt;:&lt;intelligent_feed_name&gt;
 * 
 * ```sh
 * $ pulumi import cloudngfwaws:index/intelligentFeed:IntelligentFeed example Local:terraform-rulestack:tf-feed
 * ```
 * 
 */
@ResourceType(type="cloudngfwaws:index/intelligentFeed:IntelligentFeed")
public class IntelligentFeed extends com.pulumi.resources.CustomResource {
    /**
     * The audit comment.
     * 
     */
    @Export(name="auditComment", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> auditComment;

    /**
     * @return The audit comment.
     * 
     */
    public Output<Optional<String>> auditComment() {
        return Codegen.optional(this.auditComment);
    }
    /**
     * The certificate profile.
     * 
     */
    @Export(name="certificate", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> certificate;

    /**
     * @return The certificate profile.
     * 
     */
    public Output<Optional<String>> certificate() {
        return Codegen.optional(this.certificate);
    }
    /**
     * The description.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return The description.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Update frequency. Valid values are `HOURLY` or `DAILY`. Defaults to `HOURLY`.
     * 
     */
    @Export(name="frequency", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> frequency;

    /**
     * @return Update frequency. Valid values are `HOURLY` or `DAILY`. Defaults to `HOURLY`.
     * 
     */
    public Output<Optional<String>> frequency() {
        return Codegen.optional(this.frequency);
    }
    /**
     * The name.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The rulestack.
     * 
     */
    @Export(name="rulestack", refs={String.class}, tree="[0]")
    private Output<String> rulestack;

    /**
     * @return The rulestack.
     * 
     */
    public Output<String> rulestack() {
        return this.rulestack;
    }
    /**
     * The rulestack&#39;s scope. A local rulestack will require that you&#39;ve retrieved a LRA JWT. A global rulestack will require that you&#39;ve retrieved a GRA JWT. Valid values are `Local` or `Global`. Defaults to `Local`.
     * 
     */
    @Export(name="scope", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> scope;

    /**
     * @return The rulestack&#39;s scope. A local rulestack will require that you&#39;ve retrieved a LRA JWT. A global rulestack will require that you&#39;ve retrieved a GRA JWT. Valid values are `Local` or `Global`. Defaults to `Local`.
     * 
     */
    public Output<Optional<String>> scope() {
        return Codegen.optional(this.scope);
    }
    /**
     * The time to poll for updates if frequency is daily. The number must be between [0, 23] incluside.
     * 
     */
    @Export(name="time", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> time;

    /**
     * @return The time to poll for updates if frequency is daily. The number must be between [0, 23] incluside.
     * 
     */
    public Output<Optional<Integer>> time() {
        return Codegen.optional(this.time);
    }
    /**
     * The intelligent feed type. Valid values are `IP_LIST` or `URL_LIST`. Defaults to `IP_LIST`.
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> type;

    /**
     * @return The intelligent feed type. Valid values are `IP_LIST` or `URL_LIST`. Defaults to `IP_LIST`.
     * 
     */
    public Output<Optional<String>> type() {
        return Codegen.optional(this.type);
    }
    /**
     * The update token.
     * 
     */
    @Export(name="updateToken", refs={String.class}, tree="[0]")
    private Output<String> updateToken;

    /**
     * @return The update token.
     * 
     */
    public Output<String> updateToken() {
        return this.updateToken;
    }
    /**
     * The intelligent feed source.
     * 
     */
    @Export(name="url", refs={String.class}, tree="[0]")
    private Output<String> url;

    /**
     * @return The intelligent feed source.
     * 
     */
    public Output<String> url() {
        return this.url;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public IntelligentFeed(java.lang.String name) {
        this(name, IntelligentFeedArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public IntelligentFeed(java.lang.String name, IntelligentFeedArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public IntelligentFeed(java.lang.String name, IntelligentFeedArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cloudngfwaws:index/intelligentFeed:IntelligentFeed", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private IntelligentFeed(java.lang.String name, Output<java.lang.String> id, @Nullable IntelligentFeedState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cloudngfwaws:index/intelligentFeed:IntelligentFeed", name, state, makeResourceOptions(options, id), false);
    }

    private static IntelligentFeedArgs makeArgs(IntelligentFeedArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? IntelligentFeedArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static IntelligentFeed get(java.lang.String name, Output<java.lang.String> id, @Nullable IntelligentFeedState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new IntelligentFeed(name, id, state, options);
    }
}
