// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudngfwaws;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PredefinedUrlCategoryOverrideArgs extends com.pulumi.resources.ResourceArgs {

    public static final PredefinedUrlCategoryOverrideArgs Empty = new PredefinedUrlCategoryOverrideArgs();

    /**
     * The action to take. Valid values are `none`, `allow`, `alert`, or `block`. Defaults to `none`.
     * 
     */
    @Import(name="action")
    private @Nullable Output<String> action;

    /**
     * @return The action to take. Valid values are `none`, `allow`, `alert`, or `block`. Defaults to `none`.
     * 
     */
    public Optional<Output<String>> action() {
        return Optional.ofNullable(this.action);
    }

    /**
     * The audit comment.
     * 
     */
    @Import(name="auditComment")
    private @Nullable Output<String> auditComment;

    /**
     * @return The audit comment.
     * 
     */
    public Optional<Output<String>> auditComment() {
        return Optional.ofNullable(this.auditComment);
    }

    /**
     * The name.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The rulestack.
     * 
     */
    @Import(name="rulestack", required=true)
    private Output<String> rulestack;

    /**
     * @return The rulestack.
     * 
     */
    public Output<String> rulestack() {
        return this.rulestack;
    }

    private PredefinedUrlCategoryOverrideArgs() {}

    private PredefinedUrlCategoryOverrideArgs(PredefinedUrlCategoryOverrideArgs $) {
        this.action = $.action;
        this.auditComment = $.auditComment;
        this.name = $.name;
        this.rulestack = $.rulestack;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PredefinedUrlCategoryOverrideArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PredefinedUrlCategoryOverrideArgs $;

        public Builder() {
            $ = new PredefinedUrlCategoryOverrideArgs();
        }

        public Builder(PredefinedUrlCategoryOverrideArgs defaults) {
            $ = new PredefinedUrlCategoryOverrideArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param action The action to take. Valid values are `none`, `allow`, `alert`, or `block`. Defaults to `none`.
         * 
         * @return builder
         * 
         */
        public Builder action(@Nullable Output<String> action) {
            $.action = action;
            return this;
        }

        /**
         * @param action The action to take. Valid values are `none`, `allow`, `alert`, or `block`. Defaults to `none`.
         * 
         * @return builder
         * 
         */
        public Builder action(String action) {
            return action(Output.of(action));
        }

        /**
         * @param auditComment The audit comment.
         * 
         * @return builder
         * 
         */
        public Builder auditComment(@Nullable Output<String> auditComment) {
            $.auditComment = auditComment;
            return this;
        }

        /**
         * @param auditComment The audit comment.
         * 
         * @return builder
         * 
         */
        public Builder auditComment(String auditComment) {
            return auditComment(Output.of(auditComment));
        }

        /**
         * @param name The name.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param rulestack The rulestack.
         * 
         * @return builder
         * 
         */
        public Builder rulestack(Output<String> rulestack) {
            $.rulestack = rulestack;
            return this;
        }

        /**
         * @param rulestack The rulestack.
         * 
         * @return builder
         * 
         */
        public Builder rulestack(String rulestack) {
            return rulestack(Output.of(rulestack));
        }

        public PredefinedUrlCategoryOverrideArgs build() {
            if ($.rulestack == null) {
                throw new MissingRequiredPropertyException("PredefinedUrlCategoryOverrideArgs", "rulestack");
            }
            return $;
        }
    }

}
