// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws.Inputs
{

    public sealed class NgfwLogProfileLogConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Type of Role for log configuration
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// The log destination details.
        /// </summary>
        [Input("logDestination", required: true)]
        public Input<string> LogDestination { get; set; } = null!;

        /// <summary>
        /// The log destination type. Valid values are `S3`, `CloudWatchLogs`, or `KinesisDataFirehose`.
        /// </summary>
        [Input("logDestinationType", required: true)]
        public Input<string> LogDestinationType { get; set; } = null!;

        [Input("logTypes", required: true)]
        private InputList<string>? _logTypes;

        /// <summary>
        /// The list of different log types that are wanted
        /// </summary>
        public InputList<string> LogTypes
        {
            get => _logTypes ?? (_logTypes = new InputList<string>());
            set => _logTypes = value;
        }

        /// <summary>
        /// Type of Role for log configuration
        /// </summary>
        [Input("roleType")]
        public Input<string>? RoleType { get; set; }

        public NgfwLogProfileLogConfigGetArgs()
        {
        }
        public static new NgfwLogProfileLogConfigGetArgs Empty => new NgfwLogProfileLogConfigGetArgs();
    }
}
