// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws.Inputs
{

    public sealed class NgfwEndpointPrefixPrivatePrefixArgs : global::Pulumi.ResourceArgs
    {
        [Input("cidrs")]
        private InputList<string>? _cidrs;
        public InputList<string> Cidrs
        {
            get => _cidrs ?? (_cidrs = new InputList<string>());
            set => _cidrs = value;
        }

        public NgfwEndpointPrefixPrivatePrefixArgs()
        {
        }
        public static new NgfwEndpointPrefixPrivatePrefixArgs Empty => new NgfwEndpointPrefixPrivatePrefixArgs();
    }
}
