// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws.Inputs
{

    public sealed class NgfwEndpointPrefixGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("privatePrefixes")]
        private InputList<Inputs.NgfwEndpointPrefixPrivatePrefixGetArgs>? _privatePrefixes;
        public InputList<Inputs.NgfwEndpointPrefixPrivatePrefixGetArgs> PrivatePrefixes
        {
            get => _privatePrefixes ?? (_privatePrefixes = new InputList<Inputs.NgfwEndpointPrefixPrivatePrefixGetArgs>());
            set => _privatePrefixes = value;
        }

        public NgfwEndpointPrefixGetArgs()
        {
        }
        public static new NgfwEndpointPrefixGetArgs Empty => new NgfwEndpointPrefixGetArgs();
    }
}
