// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudNgfwAws.Inputs
{

    public sealed class NgfwStatusGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("attachments")]
        private InputList<Inputs.NgfwStatusAttachmentGetArgs>? _attachments;

        /// <summary>
        /// The firewall attachments.
        /// </summary>
        public InputList<Inputs.NgfwStatusAttachmentGetArgs> Attachments
        {
            get => _attachments ?? (_attachments = new InputList<Inputs.NgfwStatusAttachmentGetArgs>());
            set => _attachments = value;
        }

        /// <summary>
        /// The firewall failure reason.
        /// </summary>
        [Input("failureReason")]
        public Input<string>? FailureReason { get; set; }

        /// <summary>
        /// The firewall status.
        /// </summary>
        [Input("firewallStatus")]
        public Input<string>? FirewallStatus { get; set; }

        /// <summary>
        /// The rulestack status.
        /// </summary>
        [Input("rulestackStatus")]
        public Input<string>? RulestackStatus { get; set; }

        public NgfwStatusGetArgs()
        {
        }
        public static new NgfwStatusGetArgs Empty => new NgfwStatusGetArgs();
    }
}
