// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Resource for Account Onboarding.
 *
 * ## Admin Permission Type
 *
 * * `Rulestack` (for `scope="Local"`)
 * * `Global Rulestack` (for `scope="Global"`)
 */
export class AccountOnboardingStack extends pulumi.CustomResource {
    /**
     * Get an existing AccountOnboardingStack resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AccountOnboardingStackState, opts?: pulumi.CustomResourceOptions): AccountOnboardingStack {
        return new AccountOnboardingStack(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cloudngfwaws:index/accountOnboardingStack:AccountOnboardingStack';

    /**
     * Returns true if the given object is an instance of AccountOnboardingStack.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AccountOnboardingStack {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AccountOnboardingStack.__pulumiType;
    }

    /**
     * The account IDs
     */
    declare public readonly accountId: pulumi.Output<string>;
    /**
     * Audit Log Group Name
     */
    declare public readonly auditlogGroup: pulumi.Output<string | undefined>;
    /**
     * Role name to run the account onboarding CFT in each account to be onboarded.
     */
    declare public readonly cftRoleName: pulumi.Output<string>;
    /**
     * Cloudwatch Log Group
     */
    declare public readonly cloudwatchLogGroup: pulumi.Output<string | undefined>;
    /**
     * Cloudwatch Namespace
     */
    declare public readonly cloudwatchNamespace: pulumi.Output<string | undefined>;
    /**
     * The CloudNGFW can decrypt inbound and outbound traffic by providing a
     * 					  certificate stored in secret Manager.
     * 		 			  The role allows the service to access a certificate configured in the rulestack.
     * 		 			  Only certificated tagged with PaloAltoCloudNGFW can be accessed
     */
    declare public readonly decryptionCert: pulumi.Output<string | undefined>;
    /**
     * Controls whether cloud NGFW will create firewall endpoints automatitically in customer subnets
     */
    declare public readonly endpointMode: pulumi.Output<string | undefined>;
    /**
     * External Id of the onboarded account
     */
    declare public readonly externalId: pulumi.Output<string>;
    /**
     * Kinesis Firehose for logging
     */
    declare public readonly kinesisFirehose: pulumi.Output<string | undefined>;
    /**
     * Role name to run the account onboarding CFT in each account to be onboarded.
     */
    declare public readonly onboardingCft: pulumi.Output<string>;
    /**
     * S3 Bucket Name for Logging. Logging roles provide access to create log contents in this bucket.
     */
    declare public readonly s3Bucket: pulumi.Output<string | undefined>;
    /**
     * SNS topic ARN to publish the role ARNs
     */
    declare public readonly snsTopicArn: pulumi.Output<string>;
    /**
     * ID of the account onboarding CFT stack
     */
    declare public readonly stackId: pulumi.Output<string>;
    /**
     * Status of the account onboarding CFT stack.
     */
    declare public readonly stackStatus: pulumi.Output<string>;
    /**
     * PANW Cloud NGFW trusted account Id
     */
    declare public readonly trustedAccount: pulumi.Output<string>;

    /**
     * Create a AccountOnboardingStack resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AccountOnboardingStackArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AccountOnboardingStackArgs | AccountOnboardingStackState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AccountOnboardingStackState | undefined;
            resourceInputs["accountId"] = state?.accountId;
            resourceInputs["auditlogGroup"] = state?.auditlogGroup;
            resourceInputs["cftRoleName"] = state?.cftRoleName;
            resourceInputs["cloudwatchLogGroup"] = state?.cloudwatchLogGroup;
            resourceInputs["cloudwatchNamespace"] = state?.cloudwatchNamespace;
            resourceInputs["decryptionCert"] = state?.decryptionCert;
            resourceInputs["endpointMode"] = state?.endpointMode;
            resourceInputs["externalId"] = state?.externalId;
            resourceInputs["kinesisFirehose"] = state?.kinesisFirehose;
            resourceInputs["onboardingCft"] = state?.onboardingCft;
            resourceInputs["s3Bucket"] = state?.s3Bucket;
            resourceInputs["snsTopicArn"] = state?.snsTopicArn;
            resourceInputs["stackId"] = state?.stackId;
            resourceInputs["stackStatus"] = state?.stackStatus;
            resourceInputs["trustedAccount"] = state?.trustedAccount;
        } else {
            const args = argsOrState as AccountOnboardingStackArgs | undefined;
            if (args?.accountId === undefined && !opts.urn) {
                throw new Error("Missing required property 'accountId'");
            }
            if (args?.cftRoleName === undefined && !opts.urn) {
                throw new Error("Missing required property 'cftRoleName'");
            }
            if (args?.externalId === undefined && !opts.urn) {
                throw new Error("Missing required property 'externalId'");
            }
            if (args?.onboardingCft === undefined && !opts.urn) {
                throw new Error("Missing required property 'onboardingCft'");
            }
            if (args?.snsTopicArn === undefined && !opts.urn) {
                throw new Error("Missing required property 'snsTopicArn'");
            }
            if (args?.trustedAccount === undefined && !opts.urn) {
                throw new Error("Missing required property 'trustedAccount'");
            }
            resourceInputs["accountId"] = args?.accountId;
            resourceInputs["auditlogGroup"] = args?.auditlogGroup;
            resourceInputs["cftRoleName"] = args?.cftRoleName;
            resourceInputs["cloudwatchLogGroup"] = args?.cloudwatchLogGroup;
            resourceInputs["cloudwatchNamespace"] = args?.cloudwatchNamespace;
            resourceInputs["decryptionCert"] = args?.decryptionCert;
            resourceInputs["endpointMode"] = args?.endpointMode;
            resourceInputs["externalId"] = args?.externalId;
            resourceInputs["kinesisFirehose"] = args?.kinesisFirehose;
            resourceInputs["onboardingCft"] = args?.onboardingCft;
            resourceInputs["s3Bucket"] = args?.s3Bucket;
            resourceInputs["snsTopicArn"] = args?.snsTopicArn;
            resourceInputs["stackId"] = args?.stackId;
            resourceInputs["stackStatus"] = args?.stackStatus;
            resourceInputs["trustedAccount"] = args?.trustedAccount;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AccountOnboardingStack.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AccountOnboardingStack resources.
 */
export interface AccountOnboardingStackState {
    /**
     * The account IDs
     */
    accountId?: pulumi.Input<string>;
    /**
     * Audit Log Group Name
     */
    auditlogGroup?: pulumi.Input<string>;
    /**
     * Role name to run the account onboarding CFT in each account to be onboarded.
     */
    cftRoleName?: pulumi.Input<string>;
    /**
     * Cloudwatch Log Group
     */
    cloudwatchLogGroup?: pulumi.Input<string>;
    /**
     * Cloudwatch Namespace
     */
    cloudwatchNamespace?: pulumi.Input<string>;
    /**
     * The CloudNGFW can decrypt inbound and outbound traffic by providing a
     * 					  certificate stored in secret Manager.
     * 		 			  The role allows the service to access a certificate configured in the rulestack.
     * 		 			  Only certificated tagged with PaloAltoCloudNGFW can be accessed
     */
    decryptionCert?: pulumi.Input<string>;
    /**
     * Controls whether cloud NGFW will create firewall endpoints automatitically in customer subnets
     */
    endpointMode?: pulumi.Input<string>;
    /**
     * External Id of the onboarded account
     */
    externalId?: pulumi.Input<string>;
    /**
     * Kinesis Firehose for logging
     */
    kinesisFirehose?: pulumi.Input<string>;
    /**
     * Role name to run the account onboarding CFT in each account to be onboarded.
     */
    onboardingCft?: pulumi.Input<string>;
    /**
     * S3 Bucket Name for Logging. Logging roles provide access to create log contents in this bucket.
     */
    s3Bucket?: pulumi.Input<string>;
    /**
     * SNS topic ARN to publish the role ARNs
     */
    snsTopicArn?: pulumi.Input<string>;
    /**
     * ID of the account onboarding CFT stack
     */
    stackId?: pulumi.Input<string>;
    /**
     * Status of the account onboarding CFT stack.
     */
    stackStatus?: pulumi.Input<string>;
    /**
     * PANW Cloud NGFW trusted account Id
     */
    trustedAccount?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AccountOnboardingStack resource.
 */
export interface AccountOnboardingStackArgs {
    /**
     * The account IDs
     */
    accountId: pulumi.Input<string>;
    /**
     * Audit Log Group Name
     */
    auditlogGroup?: pulumi.Input<string>;
    /**
     * Role name to run the account onboarding CFT in each account to be onboarded.
     */
    cftRoleName: pulumi.Input<string>;
    /**
     * Cloudwatch Log Group
     */
    cloudwatchLogGroup?: pulumi.Input<string>;
    /**
     * Cloudwatch Namespace
     */
    cloudwatchNamespace?: pulumi.Input<string>;
    /**
     * The CloudNGFW can decrypt inbound and outbound traffic by providing a
     * 					  certificate stored in secret Manager.
     * 		 			  The role allows the service to access a certificate configured in the rulestack.
     * 		 			  Only certificated tagged with PaloAltoCloudNGFW can be accessed
     */
    decryptionCert?: pulumi.Input<string>;
    /**
     * Controls whether cloud NGFW will create firewall endpoints automatitically in customer subnets
     */
    endpointMode?: pulumi.Input<string>;
    /**
     * External Id of the onboarded account
     */
    externalId: pulumi.Input<string>;
    /**
     * Kinesis Firehose for logging
     */
    kinesisFirehose?: pulumi.Input<string>;
    /**
     * Role name to run the account onboarding CFT in each account to be onboarded.
     */
    onboardingCft: pulumi.Input<string>;
    /**
     * S3 Bucket Name for Logging. Logging roles provide access to create log contents in this bucket.
     */
    s3Bucket?: pulumi.Input<string>;
    /**
     * SNS topic ARN to publish the role ARNs
     */
    snsTopicArn: pulumi.Input<string>;
    /**
     * ID of the account onboarding CFT stack
     */
    stackId?: pulumi.Input<string>;
    /**
     * Status of the account onboarding CFT stack.
     */
    stackStatus?: pulumi.Input<string>;
    /**
     * PANW Cloud NGFW trusted account Id
     */
    trustedAccount: pulumi.Input<string>;
}
