// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Resource for fqdn list manipulation.
 *
 * ## Admin Permission Type
 *
 * * `Rulestack` (for `scope="Local"`)
 * * `Global Rulestack` (for `scope="Global"`)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudngfwaws from "@pulumi/cloudngfwaws";
 *
 * const r = new cloudngfwaws.Rulestack("r", {
 *     name: "terraform-rulestack",
 *     scope: "Local",
 *     accountId: "123456789",
 *     description: "Made by Pulumi",
 *     profileConfig: {
 *         antiSpyware: "BestPractice",
 *     },
 * });
 * const example = new cloudngfwaws.FqdnList("example", {
 *     rulestack: r.name,
 *     name: "tf-fqdn-list",
 *     description: "Also configured by Terraform",
 *     fqdnLists: [
 *         "example.com",
 *         "foobar.org",
 *     ],
 *     auditComment: "initial config",
 * });
 * ```
 *
 * ## Import
 *
 * import name is <scope>:<rulestack>:<fqdn_list_name>
 *
 * ```sh
 * $ pulumi import cloudngfwaws:index/fqdnList:FqdnList example Local:terraform-rulestack:tf-fqdn-list
 * ```
 */
export class FqdnList extends pulumi.CustomResource {
    /**
     * Get an existing FqdnList resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FqdnListState, opts?: pulumi.CustomResourceOptions): FqdnList {
        return new FqdnList(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cloudngfwaws:index/fqdnList:FqdnList';

    /**
     * Returns true if the given object is an instance of FqdnList.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FqdnList {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FqdnList.__pulumiType;
    }

    /**
     * The audit comment.
     */
    declare public readonly auditComment: pulumi.Output<string | undefined>;
    /**
     * The description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The fqdn list.
     */
    declare public readonly fqdnLists: pulumi.Output<string[]>;
    /**
     * The name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The rulestack.
     */
    declare public readonly rulestack: pulumi.Output<string>;
    /**
     * The rulestack's scope. A local rulestack will require that you've retrieved a LRA JWT. A global rulestack will require that you've retrieved a GRA JWT. Valid values are `Local` or `Global`. Defaults to `Local`.
     */
    declare public readonly scope: pulumi.Output<string | undefined>;
    /**
     * The update token.
     */
    declare public /*out*/ readonly updateToken: pulumi.Output<string>;

    /**
     * Create a FqdnList resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FqdnListArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FqdnListArgs | FqdnListState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FqdnListState | undefined;
            resourceInputs["auditComment"] = state?.auditComment;
            resourceInputs["description"] = state?.description;
            resourceInputs["fqdnLists"] = state?.fqdnLists;
            resourceInputs["name"] = state?.name;
            resourceInputs["rulestack"] = state?.rulestack;
            resourceInputs["scope"] = state?.scope;
            resourceInputs["updateToken"] = state?.updateToken;
        } else {
            const args = argsOrState as FqdnListArgs | undefined;
            if (args?.fqdnLists === undefined && !opts.urn) {
                throw new Error("Missing required property 'fqdnLists'");
            }
            if (args?.rulestack === undefined && !opts.urn) {
                throw new Error("Missing required property 'rulestack'");
            }
            resourceInputs["auditComment"] = args?.auditComment;
            resourceInputs["description"] = args?.description;
            resourceInputs["fqdnLists"] = args?.fqdnLists;
            resourceInputs["name"] = args?.name;
            resourceInputs["rulestack"] = args?.rulestack;
            resourceInputs["scope"] = args?.scope;
            resourceInputs["updateToken"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FqdnList.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FqdnList resources.
 */
export interface FqdnListState {
    /**
     * The audit comment.
     */
    auditComment?: pulumi.Input<string>;
    /**
     * The description.
     */
    description?: pulumi.Input<string>;
    /**
     * The fqdn list.
     */
    fqdnLists?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name.
     */
    name?: pulumi.Input<string>;
    /**
     * The rulestack.
     */
    rulestack?: pulumi.Input<string>;
    /**
     * The rulestack's scope. A local rulestack will require that you've retrieved a LRA JWT. A global rulestack will require that you've retrieved a GRA JWT. Valid values are `Local` or `Global`. Defaults to `Local`.
     */
    scope?: pulumi.Input<string>;
    /**
     * The update token.
     */
    updateToken?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a FqdnList resource.
 */
export interface FqdnListArgs {
    /**
     * The audit comment.
     */
    auditComment?: pulumi.Input<string>;
    /**
     * The description.
     */
    description?: pulumi.Input<string>;
    /**
     * The fqdn list.
     */
    fqdnLists: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name.
     */
    name?: pulumi.Input<string>;
    /**
     * The rulestack.
     */
    rulestack: pulumi.Input<string>;
    /**
     * The rulestack's scope. A local rulestack will require that you've retrieved a LRA JWT. A global rulestack will require that you've retrieved a GRA JWT. Valid values are `Local` or `Global`. Defaults to `Local`.
     */
    scope?: pulumi.Input<string>;
}
