// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Data source for retrieving account information.
 *
 * ## Admin Permission Type
 *
 * * `Rulestack` (for `scope="Local"`)
 * * `Global Rulestack` (for `scope="Global"`)
 */
export function getAccount(args?: GetAccountArgs, opts?: pulumi.InvokeOptions): Promise<GetAccountResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cloudngfwaws:index/getAccount:getAccount", {
        "accountId": args.accountId,
        "cftUrl": args.cftUrl,
        "externalId": args.externalId,
        "onboardingStatus": args.onboardingStatus,
        "origin": args.origin,
        "serviceAccountId": args.serviceAccountId,
        "snsTopicArn": args.snsTopicArn,
        "trustedAccount": args.trustedAccount,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccount.
 */
export interface GetAccountArgs {
    /**
     * The account ID
     */
    accountId?: string;
    /**
     * The CFT URL.
     */
    cftUrl?: string;
    /**
     * The external ID of the account
     */
    externalId?: string;
    /**
     * The Account onboarding status
     */
    onboardingStatus?: string;
    /**
     * Origin of account onboarding
     */
    origin?: string;
    /**
     * The account ID of cloud NGFW service
     */
    serviceAccountId?: string;
    /**
     * The SNS topic ARN
     */
    snsTopicArn?: string;
    /**
     * The trusted account ID
     */
    trustedAccount?: string;
}

/**
 * A collection of values returned by getAccount.
 */
export interface GetAccountResult {
    /**
     * The account ID
     */
    readonly accountId?: string;
    /**
     * The CFT URL.
     */
    readonly cftUrl: string;
    /**
     * The external ID of the account
     */
    readonly externalId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The Account onboarding status
     */
    readonly onboardingStatus: string;
    /**
     * Origin of account onboarding
     */
    readonly origin: string;
    /**
     * The account ID of cloud NGFW service
     */
    readonly serviceAccountId: string;
    /**
     * The SNS topic ARN
     */
    readonly snsTopicArn: string;
    /**
     * The trusted account ID
     */
    readonly trustedAccount: string;
    /**
     * The update token.
     */
    readonly updateToken: string;
}
/**
 * Data source for retrieving account information.
 *
 * ## Admin Permission Type
 *
 * * `Rulestack` (for `scope="Local"`)
 * * `Global Rulestack` (for `scope="Global"`)
 */
export function getAccountOutput(args?: GetAccountOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAccountResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cloudngfwaws:index/getAccount:getAccount", {
        "accountId": args.accountId,
        "cftUrl": args.cftUrl,
        "externalId": args.externalId,
        "onboardingStatus": args.onboardingStatus,
        "origin": args.origin,
        "serviceAccountId": args.serviceAccountId,
        "snsTopicArn": args.snsTopicArn,
        "trustedAccount": args.trustedAccount,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccount.
 */
export interface GetAccountOutputArgs {
    /**
     * The account ID
     */
    accountId?: pulumi.Input<string>;
    /**
     * The CFT URL.
     */
    cftUrl?: pulumi.Input<string>;
    /**
     * The external ID of the account
     */
    externalId?: pulumi.Input<string>;
    /**
     * The Account onboarding status
     */
    onboardingStatus?: pulumi.Input<string>;
    /**
     * Origin of account onboarding
     */
    origin?: pulumi.Input<string>;
    /**
     * The account ID of cloud NGFW service
     */
    serviceAccountId?: pulumi.Input<string>;
    /**
     * The SNS topic ARN
     */
    snsTopicArn?: pulumi.Input<string>;
    /**
     * The trusted account ID
     */
    trustedAccount?: pulumi.Input<string>;
}
