// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Data source for retrieving intelligent feed information.
 *
 * ## Admin Permission Type
 *
 * * `Rulestack` (for `scope="Local"`)
 * * `Global Rulestack` (for `scope="Global"`)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudngfwaws from "@pulumi/cloudngfwaws";
 *
 * const r = new cloudngfwaws.Rulestack("r", {
 *     name: "my-rulestack",
 *     scope: "Local",
 *     accountId: "12345",
 *     description: "Made by Pulumi",
 *     profileConfig: {
 *         antiSpyware: "BestPractice",
 *     },
 * });
 * const example = cloudngfwaws.getIntelligentFeedOutput({
 *     rulestack: r.name,
 *     name: "foobar",
 * });
 * ```
 */
export function getIntelligentFeed(args: GetIntelligentFeedArgs, opts?: pulumi.InvokeOptions): Promise<GetIntelligentFeedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cloudngfwaws:index/getIntelligentFeed:getIntelligentFeed", {
        "configType": args.configType,
        "name": args.name,
        "rulestack": args.rulestack,
        "scope": args.scope,
    }, opts);
}

/**
 * A collection of arguments for invoking getIntelligentFeed.
 */
export interface GetIntelligentFeedArgs {
    /**
     * Retrieve either the candidate or running config. Valid values are `candidate` or `running`. Defaults to `candidate`.
     */
    configType?: string;
    /**
     * The name.
     */
    name: string;
    /**
     * The rulestack.
     */
    rulestack: string;
    /**
     * The rulestack's scope. A local rulestack will require that you've retrieved a LRA JWT. A global rulestack will require that you've retrieved a GRA JWT. Valid values are `Local` or `Global`. Defaults to `Local`.
     */
    scope?: string;
}

/**
 * A collection of values returned by getIntelligentFeed.
 */
export interface GetIntelligentFeedResult {
    /**
     * The audit comment.
     */
    readonly auditComment: string;
    /**
     * The certificate profile.
     */
    readonly certificate: string;
    /**
     * Retrieve either the candidate or running config. Valid values are `candidate` or `running`. Defaults to `candidate`.
     */
    readonly configType?: string;
    /**
     * The description.
     */
    readonly description: string;
    /**
     * Update frequency. Valid values are `HOURLY` or `DAILY`.
     */
    readonly frequency: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name.
     */
    readonly name: string;
    /**
     * The rulestack.
     */
    readonly rulestack: string;
    /**
     * The rulestack's scope. A local rulestack will require that you've retrieved a LRA JWT. A global rulestack will require that you've retrieved a GRA JWT. Valid values are `Local` or `Global`. Defaults to `Local`.
     */
    readonly scope?: string;
    /**
     * The time to poll for updates if frequency is daily. The number must be between [0, 23] incluside.
     */
    readonly time: number;
    /**
     * The intelligent feed type. Valid values are `IP_LIST` or `URL_LIST`.
     */
    readonly type: string;
    /**
     * The update token.
     */
    readonly updateToken: string;
    /**
     * The intelligent feed source.
     */
    readonly url: string;
}
/**
 * Data source for retrieving intelligent feed information.
 *
 * ## Admin Permission Type
 *
 * * `Rulestack` (for `scope="Local"`)
 * * `Global Rulestack` (for `scope="Global"`)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudngfwaws from "@pulumi/cloudngfwaws";
 *
 * const r = new cloudngfwaws.Rulestack("r", {
 *     name: "my-rulestack",
 *     scope: "Local",
 *     accountId: "12345",
 *     description: "Made by Pulumi",
 *     profileConfig: {
 *         antiSpyware: "BestPractice",
 *     },
 * });
 * const example = cloudngfwaws.getIntelligentFeedOutput({
 *     rulestack: r.name,
 *     name: "foobar",
 * });
 * ```
 */
export function getIntelligentFeedOutput(args: GetIntelligentFeedOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIntelligentFeedResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cloudngfwaws:index/getIntelligentFeed:getIntelligentFeed", {
        "configType": args.configType,
        "name": args.name,
        "rulestack": args.rulestack,
        "scope": args.scope,
    }, opts);
}

/**
 * A collection of arguments for invoking getIntelligentFeed.
 */
export interface GetIntelligentFeedOutputArgs {
    /**
     * Retrieve either the candidate or running config. Valid values are `candidate` or `running`. Defaults to `candidate`.
     */
    configType?: pulumi.Input<string>;
    /**
     * The name.
     */
    name: pulumi.Input<string>;
    /**
     * The rulestack.
     */
    rulestack: pulumi.Input<string>;
    /**
     * The rulestack's scope. A local rulestack will require that you've retrieved a LRA JWT. A global rulestack will require that you've retrieved a GRA JWT. Valid values are `Local` or `Global`. Defaults to `Local`.
     */
    scope?: pulumi.Input<string>;
}
